name: Feature Request
description: Submit a request for a feature you would like to see in Holos.
labels: ["feature request"]
assignees:
  - aaron-mcpherson
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! 
  - type: textarea
    id: feature-request
    attributes:
      label: Feature request.
      description: What feature would you like to see in Holos?
      placeholder:
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/holos-aafc/Holos/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Holos' Code of Conduct
          required: true
