name: Holos Documentation Suggestion
description: Suggest a change to the Holos documentation.
labels: ["suggestion", "documentation"]
assignees:
  - aaron-mcpherson
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make this suggestion!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need to contact you directly?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Your suggestion.
      description: What additions, removal or changes would you like to suggest to the Holos documentation?
      placeholder:
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/holos-aafc/Holos/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Holos' Code of Conduct
          required: true
