//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Content.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Content.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRUID,PRNAME,CARUID,CARNAME,Split_polys,POLY_ID,ECO_ID
        ///48,Alberta,4870,Census Agricultural Region 7,,242021,242
        ///48,Alberta,4870,Census Agricultural Region 7,,242022,242
        ///48,Alberta,4870,Census Agricultural Region 7,,242023,242
        ///48,Alberta,4860,Census Agricultural Region 6,0,242024,242
        ///48,Alberta,4870,Census Agricultural Region 7,1,242024,242
        ///48,Alberta,4870,Census Agricultural Region 7,,242025,242
        ///48,Alberta,4870,Census Agricultural Region 7,,242026,242
        ///48,Alberta,4860,Census Agricultural Region 6,0,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ab_car_to_slc {
            get {
                return ResourceManager.GetString("ab_car_to_slc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR,CARUID,PRSAD,YEAR,CROP,SEEDED,ESEED,HARV,EHARV,PERHARV,YIELD,YLDLBS,EYIELD,PRODN,PRDLBS,EPRODN,NYIELD,NYLDLBS,NEYIELD,PPYIELD
        ///48,4810,4810,1985,Barley,113000,45700,87000,35200,77.00%,41.7,-99,2200,2488,-99,54200,28.6,-99,1540,-30%
        ///48,4810,4810,1985,Canary seed,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
        ///48,4810,4810,1985,Canola,21900,8900,21900,8900,100.00%,19.6,-99,1100,405,-99,9200,18.5,-99,1034,-6%
        ///48,4810,4810,1985,Chick peas,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ab_default_yields {
            get {
                return ResourceManager.GetString("ab_default_yields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATIO_AgT,,,,,,
        ///Age,HP_Ratio_AgT,WS_Ratio_AgT,SP_Ratio_AgT,MM_Ratio_AgT,GA_Ratio_AgT,CG_Ratio_AgT
        ///1,0.5,0.333333333,0.5,0.5,0.5,0.5
        ///2,0.63577638,0.46598437,0.309915099,0.21442154,0.633449325,0.82814561
        ///3,0.682795544,0.52351062,0.393026985,0.309444082,0.680845432,0.866580809
        ///4,0.708328459,0.554135546,0.469712801,0.573688849,0.707073171,0.880614184
        ///5,0.722196319,0.573494916,0.526232539,0.659527611,0.721697977,0.887372778
        ///6,0.732407352,0.588865575,0.566276594,0.690564858,0.732400258,0.891397731
        ///7,0.739 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Agt_Ratios {
            get {
                return ResourceManager.GetString("Agt_Ratios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR,CARUID,PRSAD,YEAR,CROP,SEEDED,ESEED,HARV,EHARV,PERHARV,YIELD,YLDLBS,EYIELD,PRODN,PRDLBS,EPRODN,NYIELD,NYLDLBS,NEYIELD,PPYIELD,CSAD
        ///59,5901,5901,1985,Barley,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99.0,-99,-99,-99.00,&quot;Non Peace, 1 - British Columbia&quot;
        ///59,5901,5901,1985,Canola,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99.0,-99,-99,-99.00,&quot;Non Peace, 1 - British Columbia&quot;
        ///59,5901,5901,1985,Oats,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99.0,-99,-99,-99.00,&quot;Non Peace, 1 - British Columbia&quot;
        ///59,5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bc_default_yields {
            get {
                return ResourceManager.GetString("bc_default_yields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Z,Cluster,Mortality_pct,Year,Age,Stems,DBH_cm,Height_m,Kg_pertree,km_per_ha,Stems_tosum1ha,Biomass_Mgkm,Volume_m3km,Roots_Mgkm,Fineroots_Mgkm
        ///BLK_,BLK_1,0,2016,1,527,0.267289221,0,0.000948767,27.62313388,13811.56694,1.81E-05,0.026164808,1.81E-05,8.15E-06
        ///BLK_,BLK_1,0,2017,2,527,3.295552969,1.566848874,0.613009453,12.21011683,6105.058415,0.026458059,1.216759745,0.005822744,0.002620235
        ///BLK_,BLK_1,0,2018,3,527,5.388503551,2.254692554,2.175462246,7.573899439,3786.949719,0.151370984,3.544837902,0.0238990 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string caragana__31_allclusters_future {
            get {
                return ResourceManager.GetString("caragana__31_allclusters_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLC,Month,Tmax,Tmin,Tavg,Prec,PET
        ///11002,1,-18.21194176,-25.11742306,-21.66468221,39.69488696,0
        ///11002,2,-18.05191687,-25.16470147,-21.60830896,35.99455019,0
        ///11002,3,-13.19955646,-20.9935613,-17.09655881,36.82473015,0
        ///11002,4,-5.34409841,-12.77567809,-9.059888266,32.48345127,0
        ///11002,5,1.536666055,-4.900829907,-1.682082082,32.59340555,16.24813135
        ///11002,6,7.626342001,0.61676796,4.121554949,47.47991911,84.31680966
        ///11002,7,12.52566527,4.56587496,8.54577013,61.78348927,105.5276527
        ///11002,8,11.53468338,4.427 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string climate_norms_by_poly {
            get {
                return ResourceManager.GetString("climate_norms_by_poly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1985,1,-12.5,0,0
        ///1985,2,0,0,0
        ///1985,3,2,0,0
        ///1985,4,2,0,0
        ///1985,5,6.8,0,0
        ///1985,6,0.3,0,0
        ///1985,7,-6.8,0,0
        ///1985,8,-10,0,0
        ///1985,9,-10.8,0,0
        ///1985,10,-14.8,0,0
        ///1985,11,-6.8,0,0
        ///1985,12,2.5,0,0
        ///1985,13,-1.3,0,0
        ///1985,14,0.3,1,0
        ///1985,15,2,0,0
        ///1985,16,1.3,0,0
        ///1985,17,7,0,0
        ///1985,18,-2.8,3.5,0
        ///1985,19,-14.3,4.5,0
        ///1985,20,-16.8,0,0
        ///1985,21,-13,0,0
        ///1985,22,-6.8,0,0
        ///1985,23,-2,0,0
        ///1985,24,2.8,0,0
        ///1985,25,1.3,0,0
        ///1985,26,-4.3,0,0
        ///1985,27,-5.3,0.3,0
        ///1985,28,-5,3.3,0
        ///1985,29,-21.3,0,0
        ///1985,30,-23,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string climate_parameter_tool_input {
            get {
                return ResourceManager.GetString("climate_parameter_tool_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLY_ID,CMP,PERCENT,SLOPE,STONE,LOCSF,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOIL_ID,CMP_ID
        ///242021,1,40,A,U,D,AB,BUF,gl~~~,N,ABBUFgl~~~N,24202101
        ///242021,2,30,A,N,U,AB,KEG,~~~~~,N,ABKEG~~~~~N,24202102
        ///242021,3,30,A,N,F13,AB,MLD,~~~~~,N,ABMLD~~~~~N,24202103
        ///242022,1,40,A,N,B07,AB,MKW,~~~~~,N,ABMKW~~~~~N,24202201
        ///242022,2,30,A,N,F13,AB,MLD,~~~~~,N,ABMLD~~~~~N,24202202
        ///242022,3,30,A,N,U,AB,SEN,~~~~~,N,ABSEN~~~~~N,24202203
        ///242023,1,40,A,N,B07,AB,MKW,~~~~~,N,ABMKW~~~~~N,24202301
        ///242023,2,30,A,N,F13,AB,MLD,~~ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cmp {
            get {
                return ResourceManager.GetString("cmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE: Nutrient Composition and Variability of Some Feedstuffs Commonly Fed to Dairy Cattle (all values on a dry basis) ,,,,,,,,,,,,,,,,,,
        ///#,Feed,Class,TDN (1 x %),DM (%),CP (%),NDICP (%),ADICP (%),EE (%),NDF (%),ADF (%),Lignin (%),Ash (%),DE-1x (Mcal/kg,ME-3x (Mcal/kg),NEL-3x (Mcal/kg),NEL-4x (Mcal/kg),NEM-3x (Mcal/kg),NEG-3x (Mcal/kg)
        ///1,ALFALFA (Medicago Sativa  17% CP),Forage,56.4,90.3,19.2,3.1,2.4,2.5,41.6,32.8,7.6,11,2.6,1.96,1.19,1.11,1.27,0.7
        ///2,ALMOND Hulls,Conc,58.4,86.9,6.5,2.3,1.8,2.9,36.8,28.7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dairy_feed_composition {
            get {
                return ResourceManager.GetString("dairy_feed_composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecodistrict,Ecozone,Province,PMayToOct,PEMayToOct,Ftopo,SoilType,SoilTexture
        ///358,Boreal Shield West,Manitoba,348,453,0,Brown Chernozem,Coarse
        ///358,Boreal Shield West,Saskatchewan,348,453,0,Brown Chernozem,Coarse
        ///371,Boreal Shield West,Manitoba,376,581,0.33,Black/Gray Chernozem,Fine
        ///371,Boreal Shield West,Ontario,376,581,0.33,Eastern Canada,Fine
        ///375,Boreal Shield West,Manitoba,411,579,0.33,Black/Gray Chernozem,Fine
        ///377,Boreal Shield West,Manitoba,501,492,3.38,Eastern Canada,Fine
        ///377,Boreal Shield West, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ecodistrict_to_ecozone_mapping {
            get {
                return ResourceManager.GetString("ecodistrict_to_ecozone_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECODISTRIC,NAME_EN
        ///1,Northern Ellesmere Ice Cap
        ///2,Agassiz Ice Cap and Prince of Wales Ice Field
        ///3,Muller Ice Cap
        ///4,Devon Ice Cap
        ///5,Northen Baffin Mountains
        ///6,Southern Baffin Coastal Mountains
        ///7,Upper Hantzsch River
        ///8,Cumberland Peninsula Mountains
        ///9,Atlantic Coastal Lowlands
        ///10,Interior Coastal Lowlands
        ///11,Torngat
        ///12,Cape Chidley
        ///13,Domes
        ///14,Northwest Coast
        ///15,Southwest Ellesmere Ice Fields
        ///16,Bunde Fiord
        ///17,James Ross River
        ///18,Heintzelman Lake
        ///19,Lake Hazen
        ///20,Greely Fiord
        ///21,Eureka
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ednames {
            get {
                return ResourceManager.GetString("ednames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Alfalfa cubes,,,100,91,18.1,39.3,8.2,,,2.1,12,1.3,45.5,7.6,56,2,1.2,0.6,31,5.1,30,30,5.5,49.3,75,75,92,1.16,0.47,1.09,1.67,1.09,0.13,,1.14,,0.9,0.33,1.29,1.49,0.28,0.28,0.7,2.05,0.16,0.25,0.77,8.54,,648.5,44.1,0.8,24.3,19.3,1,
        ///2,Alfalfa dehy,,,100,93.8,18.5,28,17,,,4,10.3,0.9,40.4,14.4,62.4,2.3,1.4,0.8,46,5.4,37,37,10,54.1,75,75,6,1.18,0.48,1.11,1.71,1.11,0.13,,1.17,,0.92,0.34,1.32,2.23,0.32,0.32,0.27,2.32,0.05,0.28,0.19,11.17,0.1,309,65.3,0.3,50.2,33,,91
        ///3,Alfalfa fresh,,,100,30.7,23.1,50,8.7,,,1.5,6.2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string feeds {
            get {
                return ResourceManager.GetString("feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name,geometry
        ///244061,&quot;{&quot;&quot;type&quot;&quot;:&quot;&quot;Feature&quot;&quot;,&quot;&quot;geometry&quot;&quot;:{&quot;&quot;type&quot;&quot;:&quot;&quot;Polygon&quot;&quot;,&quot;&quot;coordinates&quot;&quot;:[[[-113.958097,59.360371,0],[-113.956784,59.359349,0],[-113.950569,59.354542,0],[-113.939385,59.333388,0],[-113.920045,59.302456,0],[-113.910746,59.283058,0],[-113.908583,59.272701,0],[-113.907632,59.261931,0],[-113.909313,59.256122,0],[-113.911683,59.251864,0],[-113.909979,59.249979,0],[-113.908438,59.243545,0],[-113.905776,59.232419,0],[-113.899309,59.213678,0],[-113.902441,59.18658,0],[-113.905245,59.175026,0] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ft_AB {
            get {
                return ResourceManager.GetString("ft_AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Z,Cluster,Mortality_pct,Year,Age,Stems,DBH_cm,Height_m,Kg_pertree,km_per_ha,Stems_tosum1ha,Biomass_Mgkm,Volume_m3km,Roots_Mgkm,Fineroots_Mgkm
        ///BLK_,BLK_1,0,2016,1,751,0.813430071,0,0.133155793,7.478855154,3739.427577,0.01337103,0.294054313,0.01337103,0.006016964
        ///BLK_,BLK_1,0,2017,2,751,1.536061645,0.809283078,0.513031065,4.821803199,2410.901599,0.079905032,1.096551794,0.044391579,0.01997621
        ///BLK_,BLK_1,0,2018,3,751,2.346818924,1.182612658,1.260931611,4.196095822,2098.047911,0.225676359,2.261485222,0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string green_ash__31_allclusters_future {
            get {
                return ResourceManager.GetString("green_ash__31_allclusters_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Z,Cluster,Mortality_pct,Year,Age,Stems,DBH_cm,Height_m,Kg_pertree,km_per_ha,Stems_tosum1ha,Biomass_Mgkm,Volume_m3km,Roots_Mgkm,Fineroots_Mgkm
        ///BLK_,BLK_1,30,2020,5,249,6.056245327,6.543235302,5.767980099,5.320487677,2660.243838,0.269942741,3.430527194,0.096106215,0.043247797
        ///BLK_,BLK_1,30,2021,6,249,8.189120293,7.351447105,11.5493288,4.712381975,2356.190987,0.61026099,6.231823162,0.206424767,0.092891145
        ///BLK_,BLK_1,30,2022,7,249,10.44325542,8.074858665,20.20964813,4.252790687,2126.395344,1.183270654,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hybrid_poplar__31_allclusters_future {
            get {
                return ResourceManager.GetString("hybrid_poplar__31_allclusters_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_settings_50 {
            get {
                object obj = ResourceManager.GetObject("icons8_settings_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month of irrigation,BC,AB,SK,MB,ON,QC,Atl. Prov
        ///Irrigation volume in April,8,3.06,15.08,0.22,3.81,10.54,7.3
        ///Irrigation volume in May,8,3.06,15.08,0.22,3.81,10.54,7.3
        ///Irrigation volume in June,19.54,13.92,14.8,11.3,18.35,19.54,10.62
        ///Irrigation volume in July,27.77,42.65,29.58,48.15,41.46,32.24,27.97
        ///Irrigation volume in August,25.66,28.04,19.4,34.88,26.74,25.97,34.06
        ///Irrigation volume in September,5.51,4.63,3.03,2.61,2.91,2.71,5.63
        ///Irrigation volume in October,5.51,4.63,3.03,2.61,2.91,2.71,5.63
        ///Total [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IrrigationByMonth {
            get {
                return ResourceManager.GetString("IrrigationByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96,1970,01,01,1,-18.9,0,0
        ///96,1970,01,02,2,-17.2,0,0
        ///96,1970,01,03,3,-20.3,0,0
        ///96,1970,01,04,4,-12.8,0,0
        ///96,1970,01,05,5,-12.2,0.8,0
        ///96,1970,01,06,6,-22.2,0,0
        ///96,1970,01,07,7,-25,0.5,0
        ///96,1970,01,08,8,-17.2,2,0
        ///96,1970,01,09,9,-18.05,0.3,0
        ///96,1970,01,10,10,-21.15,0,0
        ///96,1970,01,11,11,-21.95,0,0
        ///96,1970,01,12,12,-18.6,1,0
        ///96,1970,01,13,13,-23.1,0,0
        ///96,1970,01,14,14,-28.85,0,0
        ///96,1970,01,15,15,-19.45,6.6,0
        ///96,1970,01,16,16,-12.2,3,0
        ///96,1970,01,17,17,-26.4,0,0
        ///96,1970,01,18,18,-29.15,0,0
        ///96,19 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Kapuskasing {
            get {
                return ResourceManager.GetString("Kapuskasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECTID,ECO_ID,Cluster_ID,Soil_Zone
        ///1,647,GRAY_2,GRAY
        ///2,652,GRAY_3,GRAY
        ///3,657,GRAY_2,GRAY
        ///4,658,GRAY_2,GRAY
        ///5,659,GRAY_2,GRAY
        ///6,660,GRAY_1,GRAY
        ///7,661,GRAY_2,GRAY
        ///8,672,D_GRAY_2,DARK GRAY
        ///9,680,GRAY_3,GRAY
        ///10,682,GRAY_2,GRAY
        ///11,685,GRAY_6,GRAY
        ///12,686,GRAY_3,GRAY
        ///13,687,D_GRAY_3,DARK GRAY
        ///14,689,D_GRAY_3,DARK GRAY
        ///15,690,D_GRAY_3,DARK GRAY
        ///16,691,D_GRAY_4,DARK GRAY
        ///17,693,D_GRAY_1,DARK GRAY
        ///18,694,D_GRAY_1,DARK GRAY
        ///19,695,BLK_4,BLACK
        ///20,696,D_GRAY_3,DARK GRAY
        ///21,697,D_GRAY_2,DARK GRAY
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lookup_ecodistricts_clusters {
            get {
                return ResourceManager.GetString("lookup_ecodistricts_clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Z,Cluster,Mortality_pct,Year,Age,Stems,DBH_cm,Height_m,Kg_pertree,km_per_ha,Stems_tosum1ha,Biomass_Mgkm,Volume_m3km,Roots_Mgkm,Fineroots_Mgkm
        ///BLK_,BLK_1,0,2016,1,791,0.03929482,0,0.000632111,4.747211014,2373.605507,0.000105325,0.002380612,0.000105325,4.73963E-05
        ///BLK_,BLK_1,0,2017,2,791,0.063703857,0.339404494,0.001581441,3.941596728,1970.798364,0.000317364,0.005934413,0.001278753,0.000575439
        ///BLK_,BLK_1,0,2018,3,791,0.464991033,0.972052097,0.068795711,3.535305134,1767.652567,0.015392562,0.131942381,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string manitoba_maple__31_allclusters_future {
            get {
                return ResourceManager.GetString("manitoba_maple__31_allclusters_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- saved from url=(0014)about:internet --&gt;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///		h4, form { display: inline; }
        ///
        ///		h4 { margin-left: 5px; }
        ///
        ///		form { margin-left: 15px; }
        ///
        ///		body {
        ///			margin: 0;
        ///			overflow: hidden;
        ///		}
        ///
        ///		h4 { color: white; }
        ///
        ///		#container {
        ///			background-color: transparent;
        ///			height: 100%;
        ///			width: 100%;
        ///		}
        ///
        ///		#he [rest of string was truncated]&quot;;.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Google Maps map with deck.gl to render data from a Google Spreadsheet&lt;/title&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot;&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;style&gt;
        ///           /* Always set the map height explicitly to define the size of the div
        ///        * element that contains the map.
        ///        */
        ///           #map {
        ///               height: 100%;
        ///           }
        ///
        ///           /* Optional: Makes the sample page fill the window. */
        ///           h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string map___Copy {
            get {
                return ResourceManager.GetString("map___Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR,CARUID,PRSAD,YEAR,CROP,SEEDED,ESEED,HARV,EHARV,PERHARV,YIELD,YLDLBS,EYIELD,PRODN,PRDLBS,EPRODN,NYIELD,NYLDLBS,NEYIELD,PPYIELD,
        ///46,4601,4601,1985,Barley,167000,67600,166000,67200,0.994011976,65.9,-99,3500,10939,-99,238200,66,-99,3544.64,0.012755102,
        ///46,4601,4601,1985,Canary seed,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99.00,-99,
        ///46,4601,4601,1985,Canola,116500,47100,116500,47100,1,26.8,-99,1500,3118,-99,70700,27,-99,1501.06,0.000707714,
        ///46,4601,4601,1985,Chick peas,-99,-99,-99,-99,-99,-99 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mb_default_yields {
            get {
                return ResourceManager.GetString("mb_default_yields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR,CARUID,PRSAD,YEAR,CROP,SEEDED,ESEED,HARV,EHARV,PERHARV,YIELD,YLDLBS,EYIELD,PRODN,PRDLBS,EPRODN,NYIELD,NYLDLBS,NEYIELD,PPYIELD,CSAD
        ///35,3501,3501,1985,Barley,69500,28000,69500,28000,1,67.8,-99,3700,4714,-99,102600,67.8,-99,3664,-0.01,Southern Ontario Region 1 - Ontario
        ///35,3501,3501,1985,Corn for grain,1116900,452000,1116900,452000,1,113,-99,7100,126224,-99,3206300,113.0,-99,7094,0.00,Southern Ontario Region 1 - Ontario
        ///35,3501,3501,1985,Oats,59500,24000,59500,24000,1,73.5,-99,2800,4373,-99,67500,73.5,-9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string on_default_yields {
            get {
                return ResourceManager.GetString("on_default_yields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREA,PERIMETER,POLY_ID,ECO_ID
        ///1.376666356,6.159229849,14003,14
        ///1.58033969,9.61154108,14002,14
        ///0.93250249,5.332157388,14004,14
        ///2.408006879,13.9027207,14005,14
        ///3.511283096,27.0561629,14001,14
        ///0.840566309,7.174565103,14006,14
        ///1.729422547,9.822043928,14007,14
        ///3.484609685,16.36946244,17001,17
        ///1.231991335,14.40333775,14009,14
        ///1.664047889,8.959433492,14011,14
        ///0.684304749,7.523122702,14008,14
        ///0.955917764,14.80560676,17002,17
        ///0.032024911,1.033832089,14012,14
        ///1.37990242,18.14177082,1005,1
        ///1.338231855,8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pat {
            get {
                return ResourceManager.GetString("pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR,CARUID,PRSAD,YEAR,CROP,SEEDED,ESEED,HARV,EHARV,PERHARV,YIELD,YLDLBS,EYIELD,PRODN,PRDLBS,EPRODN,NYIELD,NYLDLBS,NEYIELD,PPYIELD,CSAD
        ///24,2401,2401,1985,Barley,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,&quot;Bas-Saint-Laurent and Gaspésie-Îles de-la-Madeleine, 1 - Québec&quot;
        ///24,2401,2401,1985,Corn for grain,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,&quot;Bas-Saint-Laurent and Gaspésie-Îles de-la-Madeleine, 1 - Québec&quot;
        ///24,2401,2401,1985,Oats,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string qc_default_yields {
            get {
                return ResourceManager.GetString("qc_default_yields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group,Crop,Growing season precip + irrigation (mm),Moisture content of product (% w/w),&quot;Soil Organic C
        ///(SOC)&quot;,SOC units,&quot;Bulk density
        ///(BD)&quot;,BD units,Relative C allocation coefficient,,,,References,,N content (g N/kg),,,,References,,Fertilization,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Tillage ,,,,,,,,,,,Irrigation ,,,,,,,,,,,Pesticide ,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,Nitrogen rates (kg ha-1) calculate as Fert amount = cropNuptake / FertUseEfficiency (0.5) - SoilNsupply (if user indicates use of SoilNtest),,,,,,,,,,, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string residue_table {
            get {
                return ResourceManager.GetString("residue_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Z,Cluster,Mortality_pct,Year,Age,Stems,DBH_cm,Height_m,Kg_pertree,km_per_ha,Stems_tosum1ha,Biomass_Mgkm,Volume_m3km,Roots_Mgkm,Fineroots_Mgkm
        ///BLK_,BLK_1,0,2016,1,610,0.122228466,0,0.008196721,6.199675663,3099.837832,0.000806494,0.87517141,0.000806494,0.000362922
        ///BLK_,BLK_1,0,2017,2,610,0.427164644,1.215685368,0.086909093,4.305439211,2152.719605,0.012313389,2.834525107,0.029920969,0.013464436
        ///BLK_,BLK_1,0,2018,3,610,0.98821795,1.895201325,0.423067451,3.704292001,1852.146,0.069668145,5.672346451,0.113 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string scots_pine__31_allclusters_future {
            get {
                return ResourceManager.GetString("scots_pine__31_allclusters_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings_50_px {
            get {
                object obj = ResourceManager.GetObject("Settings_50_px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species,a,b,r^2 (%),RMSE (%),Bias (%),N,Diameter (cm),Height(m),Biomass (kg/tree),Age (yrs),Spacing (m),Mortality (%)
        ///Hybrid Poplar,0.09142,2.3011,84,39,-16,32,13.6-59.0,8.8-23.5,20.5-1520.2,13-60,0.5-10.0,0-25
        ///White Spruce,0.00660,3.1832,97,22,27,19,1.3-38.0,1.9-21.5,0.6-1128.1,6-76,0.5-4.0,0-66
        ///Scots Pine,0.43264,1.8870,74,19,1,15,17.5-63.0,6.9-16.7,93.0-326.9,15-74,1.0-3.2,0-50
        ///Manitoba Maple,0.29428,1.8980,66,32,-9,32,3.2-43.6,2.9-15.2,2.8-380.1,5-100,1.0-5.0,0-47
        ///Green Ash,0.20637,2.1217,71,48,-0. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shelterbelt_allometric_table {
            get {
                return ResourceManager.GetString("shelterbelt_allometric_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species,ECO_ID,Mortality_pct,Age,DBH_cm,Roots_kgCperTree,Fineroots_kgCperTree
        ///Caragana,709,0,1,0.267289221286774000000000000000,0.000036201540500000000000000000,0.000016290693225000000000000000
        ///Caragana,733,0,1,0.267289221286774000000000000000,0.000036201540500000000000000000,0.000016290693225000000000000000
        ///Caragana,745,0,1,0.267289221286774000000000000000,0.000036201540500000000000000000,0.000016290693225000000000000000
        ///Caragana,747,0,1,0.267289221286774000000000000000,0.000036201540500000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shelterbelt_ecodistrict_lookup_table {
            get {
                return ResourceManager.GetString("shelterbelt_ecodistrict_lookup_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLC_FULL_POLY_SQM,ECODISTRIC,ECOREGION,ECOPROVINC,ECOZONE,Zone: 0B,Zone: 1A,Zone: 1B,Zone: 2A,Zone: 2B,Zone: 3A,Zone: 3B,Zone: 4A,Zone: 4B,Zone: 5A,Zone: 5B,Zone: 6A,Zone: 6B,Zone: 7A,Zone: 7B,Zone: 8A,Zone: 8B,Zone: 9A,Tabulated Area Estimate of Plant Hardiness Zone Raster Overlapping SLC Polygon
        ///954749210.841000,647,139,9.2,9,0.000000,0.000000,0.000000,0.000000,955750000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,955750000.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shelterbelt_ecodistrict_weights {
            get {
                return ResourceManager.GetString("shelterbelt_ecodistrict_weights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species,Hardiness Zone,Mortality_pct,Age,DBH_cm min,DBH_cm max,DBH_cm mean weighted by area,Roots_kgCperTree min,Roots_kgCperTree max,Roots_kgCperTree mean weighted by area,Fineroots_kgCperTree min,Fineroots_kgCperTree max,Fineroots_kgCperTree mean weighted by area
        ///Hybrid Poplar,2A,0,1,0.443080544471741000212006156289,0.443080544471741000212006156289,0.443080544471741000212006156289,0.000422924044999998009156799705,0.000422924044999998009156799705,0.000422924044999998009156799705,0.000190315820249999009252 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shelterbelt_hardinesszone_lookup {
            get {
                return ResourceManager.GetString("shelterbelt_hardinesszone_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species,ECO_ID,Mortality_pct,Age,DBH_cm,km_per_ha,Stems_tosum1ha,Roots_Mgkm,Fineroots_Mgkm
        ///Caragana,709,0,1,0.267289221286774000000000000000,27.623133882935200000000000000000,13811.566941467600000000000000000000,0.000018100770250000000000000000,0.000008145346612500000000000000
        ///Caragana,733,0,1,0.267289221286774000000000000000,27.623133882935200000000000000000,13811.566941467600000000000000000000,0.000018100770250000000000000000,0.000008145346612500000000000000
        ///Caragana,745,0,1,0.2672892212867740000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shelterbelt_lookup_table {
            get {
                return ResourceManager.GetString("shelterbelt_lookup_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRUID,PRNAME,CARUID,CARNAME,Split_polys,POLY_ID,ECO_ID,OID_,POLY_ID_1,LAND_AREA,WATER_AREA,FRESH_AREA,OCEAN_AREA,TOTAL_AREA,OID_1,POLY_ID_12,CMP,PERCENT,SLOPE,STONE,LOCSF,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOIL_ID,CMP_ID,OID_12,ECO_ID_1,ECODISTRIC,ECOREGION,ECOPROVINC,ECOZONE,Shape_Leng,Shape_Area
        ///47,Saskatchewan,4791,Census Agricultural Region 9B,,647012,647,7720,647012,28670,1412,1412,0,30082,9731,647012,1,21,A,N,U,SK,SYA,~~~~~,A,SKSYA~~~~~A,64701201,643,647,647,139,9.2,9,1.020507299,0.041732563
        ///47,Sas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sk_car_to_slc {
            get {
                return ResourceManager.GetString("sk_car_to_slc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR,CARUID,PRSAD,YEAR,CROP,SEEDED,ESEED,HARV,EHARV,PERHARV,YIELD,YLDLBS,EYIELD,PRODN,PRDLBS,EPRODN,NYIELD,NYLDLBS,NEYIELD,PPYIELD
        ///47,all,all,1976,Barley,3100000,1255500,2950000,1194000,0.951612903,46.1,-99,2500,136000,-99,2961000,46.10169492,-99,2479.899497,-0.008040201
        ///47,all,all,1976,Canary seed,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
        ///47,all,all,1976,Canola,750000,303500,750000,303500,1,22.8,-99,1300,17100,-99,387800,22.8,-99,1277.759473,-0.017108098
        ///47,all,all,1976,Chick peas,-99,- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sk_default_yields {
            get {
                return ResourceManager.GetString("sk_default_yields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///ABABCgl~~~N,AB,ABC,gl~~~,N,1,-5,0,,LH,,,0,-,-9,-9,-9,-9,40,5.8,6.4,83,70,30,80,60,-9,20,0.1,0,0,4,5
        ///ABABCgl~~~N,AB,ABC,gl~~~,N,2,0,13,,A,e,,5,F,13,50,39,11,0.3,5.3,5.9,74,5,10,49,-9,18,8,1.35,0,0,-9,-9
        ///ABABCgl~~~N,AB,ABC,gl~~~,N,3,13,23,,AB,,,5,F,11,43,29,28,0.4,4.7,5.2,74,13,10,45,-9,28,15, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_ab {
            get {
                return ResourceManager.GetString("sl_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///BC$AR~~~~~N,BC,$AR,~~~~~,N,1,-6,0,,LFH,,,0,-,-9,-9,-9,-9,30,5.2,5.7,30,90,21,92,35,21,14,0.3,0,0,-9,-9
        ///BC$AR~~~~~N,BC,$AR,~~~~~,N,2,0,100,,R,,,-9,-,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,2.65,-9,-9,-9,-9
        ///BC$BR~~~~~N,BC,$BR,~~~~~,N,1,-4,0,,LFH,,,0,-,-9,-9,-9,-9,45,6,6.5,88,65,21,92,35,21,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_bc {
            get {
                return ResourceManager.GetString("sl_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///MB$AR~~~~~N,MB,$AR,~~~~~,N,1,-5,0,,LH,,,0,-,-9,-9,-9,-9,34.8,4.9,5.4,60,89,10,85,70,50,15,0.15,0,0,-9,0
        ///MB$AR~~~~~N,MB,$AR,~~~~~,N,2,0,100,,R,,,-9,-,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,2.8,-9,-9,-9,-9
        ///MB$CB~~~~~N,MB,$CB,~~~~~,N,1,0,20,,C,k,1,75,C,0,100,0,0,0.1,7.8,8.2,100,0,60,34,6,5,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_mb {
            get {
                return ResourceManager.GetString("sl_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///NBACD125~~A,NB,ACD,125~~,A,1,0,15,,A,p,,0,VF,7,13,57,30,4,4.9,5.4,92,28,10,53,45,41,17,1.25,1,0,-9,-9
        ///NBACD125~~A,NB,ACD,125~~,A,2,15,100,,C,g,,0,VF,5,11,58,31,1.2,6,6.5,99,16,1,42,38,36,15,1.45,3,0,-9,-9
        ///NBACD125~~N,NB,ACD,125~~,N,1,-5,0,,O,m,,-9,-,-9,-9,-9,-9,45,4.5,5,10,85,60,93,37,26,12, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_nb {
            get {
                return ResourceManager.GetString("sl_nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///NLAARE1~~~N,NL,AAR,E1~~~,N,2,-15,-1,,F,,,0,-,-9,-9,-9,-9,28,3.4,3.8,0,120,50,90,40,30,10,0.29,0,0,-9,-9
        ///NLAARE1~~~N,NL,AAR,E1~~~,N,3,-1,0,,H,,,0,-,-9,-9,-9,-9,28,3.3,3.8,0,120,50,90,40,30,10,0.38,0,0,-9,-9
        ///NLAARE1~~~N,NL,AAR,E1~~~,N,4,0,15,,A,e,,0,VF,20,60,35,5,2.1,3.5,4.2,0,14,7,42,24,18,5, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_nl {
            get {
                return ResourceManager.GetString("sl_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///NSACA4~~~~A,NS,ACA,4~~~~,A,1,0,15,,A,p,,0,VF,25,30,60,10,1,5,6,100,11,10,51,36,30,9,1,0,0,-9,-9
        ///NSACA4~~~~A,NS,ACA,4~~~~,A,2,15,100,,C,,,0,VF,25,30,60,10,0,5,6,92,6,3,43,32,28,10,2,0,0,-9,-9
        ///NSACA5~~~~A,NS,ACA,5~~~~,A,1,0,15,,A,p,,0,VF,15,20,55,25,2,5,6,100,16,3,55,41,36,15,1,0,0,-9,-9
        ///NSAC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_ns {
            get {
                return ResourceManager.GetString("sl_ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///ONABM~~~~~A,ON,ABM,~~~~~,A,1,0,20,,A,p,,0,VF,11,23,54,23,3.1,6.4,5.9,100,39,0.511,57,50,43,14,1.16,0,0,-9,-9
        ///ONABM~~~~~A,ON,ABM,~~~~~,A,2,20,39,,B,m,,0,VF,10,23,50,27,0.5,6.3,5.8,100,27,0.312,48,40,37,19,1.39,0,0,-9,-9
        ///ONABM~~~~~A,ON,ABM,~~~~~,A,3,39,78,,B,tg,,0,VF,0,8,30,62,0.2,6.7,6.2,100, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_on {
            get {
                return ResourceManager.GetString("sl_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///PEAND612~~N,PE,AND,612~~,N,1,0,10,,O,m,1,-9,-,-9,-9,-9,-9,50,5.3,6,57,147,-9,-9,-9,-9,-9,0.09,0,0,6,10
        ///PEAND612~~N,PE,AND,612~~,N,2,10,20,,O,m,2,-9,-,-9,-9,-9,-9,48,5.2,6,56,161,-9,-9,-9,-9,-9,0.12,0,0,6,5
        ///PEAND612~~N,PE,AND,612~~,N,3,20,55,,O,m,3,-9,-,-9,-9,-9,-9,40,5.2,6,54,140,-9,-9,-9,-9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_pe {
            get {
                return ResourceManager.GetString("sl_pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///QCABT50000A,QC,ABT,50000,A,1,0,17,,A,hp,,0,-,0,0,51,49,2.3,4.4,5.2,17,18,10,60,47,42,21,1.05,0,0,-9,-9
        ///QCABT50000A,QC,ABT,50000,A,2,17,29,,A,egj,,0,-,0,0,54,46,0.3,5,6.2,59,15,10,60,47,42,20,1.05,0,0,-9,-9
        ///QCABT50000A,QC,ABT,50000,A,3,29,39,,B,tgj,,0,-,0,0,52,48,0.3,5.7,6.8,68,21,3.25,49,42, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_qc {
            get {
                return ResourceManager.GetString("sl_qc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,LAYER_NO,UDEPTH,LDEPTH,HZN_LIT,HZN_MAS,HZN_SUF,HZN_MOD,COFRAG,DOMSAND,VFSAND,TSAND,TSILT,TCLAY,ORGCARB,PHCA,PH2,BASES,CEC,KSAT,KP0,KP10,KP33,KP1500,BD,EC,CACO3,VONPOST,WOOD
        ///SKADA43~~~A,SK,ADA,43~~~,A,1,0,13,,A,p,,0,VF,12,39,32,29,1.9,6.8,7,100,25,3.1,51,-9,34,21,1.4,1,0,-9,-9
        ///SKADA43~~~A,SK,ADA,43~~~,A,2,13,40,,B,m,,0,VF,13,35,32,33,1,7.2,7.4,100,24,2.35,47,-9,35,21,1.4,1,0,-9,-9
        ///SKADA43~~~A,SK,ADA,43~~~,A,3,40,100,,C,k,,0,F,11,35,32,33,0.1,8.3,8.3,100,20,2.35, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sl_sk {
            get {
                return ResourceManager.GetString("sl_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLY_ID,Zone: 0B,Zone: 1A,Zone: 1B,Zone: 2A,Zone: 2B,Zone: 3A,Zone: 3B,Zone: 4A,Zone: 4B,Zone: 5A,Zone: 5B,Zone: 6A,Zone: 6B,Zone: 7A,Zone: 7B,Zone: 8A,Zone: 8B,Zone: 9A,Sum Total Ratio Estimates of PHZ in SLC v3.2 Polygon
        ///244007,0.000000000000000000000000000000,0.000000000000000000000000000000,0.000000000000000000000000000000,0.000000000000000000000000000000,0.692235952436465000000000000000,0.307764047563535000000000000000,0.000000000000000000000000000000,0.000000000000000000000000000000,0.000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string slc_to_hardiness_zone {
            get {
                return ResourceManager.GetString("slc_to_hardiness_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///ABABCgl~~~N,AB,ABC,gl~~~,N,ATHABASCA,M,YU,0,-,I,MF,-,-,WC,-,-,TILL,-,-,,,,LU,GL,GL
        ///ABABCst~~~A,AB,ABC,st~~~,A,ATHABASCA,M,NO,0,-,W,MF,-,-,WC,-,-,TILL,-,-,,,,LU,GL,O
        ///ABABCst~~~N,AB,ABC,st~~~,N,ATHABASCA,M,NO,0,-,W,MF,-,-,WC,-,-,TILL,-,-,,,,LU,GL,O
        ///ABABC~~~~~A,AB,ABC,~~~~~,A,ATHABASCA,M,NO,0,-,W,MF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_ab {
            get {
                return ResourceManager.GetString("sn_ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///BC$AN~~~~~N,BC,$AN,~~~~~,N,ANTHROPOGENIC,U,-,-,-,-,-,-,-,-,-,-,ANTH,-,-,-,-,-,-,-,-
        ///BC$AR~~~~~N,BC,$AR,~~~~~,N,BEDROCK ACIDIC,N,NO,-,-,-,-,-,-,-,-,-,RKIA,-,-,-,-,-,-,-,-
        ///BC$BR~~~~~N,BC,$BR,~~~~~,N,BEDROCK BASIC,N,NO,-,-,-,-,-,-,-,-,-,RKIB,-,-,-,-,-,-,-,-
        ///BC$CB~~~~~N,BC,$CB,~~~~~,N,COASTAL BEACHES [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_bc {
            get {
                return ResourceManager.GetString("sn_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///MB$AR~~~~~N,MB,$AR,~~~~~,N,Acidic Bedrock,N,-,-,-,-,-,-,-,-,-,-,RKIA,-,-,-,-,-,-,-,-
        ///MB$CB~~~~~N,MB,$CB,~~~~~,N,Cobble Beach,M,YU,0,-,I,FR,-,-,UD,-,-,LACU,-,-,RG,R,O,RG,R,O
        ///MB$CR~~~~~N,MB,$CR,~~~~~,N,Carbonate Bedrock,N,NO,-,-,-,-,-,-,-,-,-,RKLS,-,-,-,-,-,-,-,-
        ///MB$ER~~~~~N,MB,$ER,~~~~~,N,Eroded S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_mb {
            get {
                return ResourceManager.GetString("sn_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///NBACD125~~A,NB,ACD,125~~,A,ACADIA,M,YB,0,-,P,MF,-,-,EA,-,-,MARI,-,-,GL,HG,R,GL,HG,R
        ///NBACD125~~N,NB,ACD,125~~,N,ACADIA,M,YB,0,-,P,MF,-,-,EA,-,-,MARI,-,-,GL,G,R,GL,G,R
        ///NBACD71~~~A,NB,ACD,71~~~,A,ACADIA,M,YB,0,-,MW,MF,-,-,AN,-,-,MARI,-,-,RG,HR,GL,RG,HR,GL
        ///NBACD71~~~N,NB,ACD,71~~~,N,ACADIA,M,YB,0,-,M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_nb {
            get {
                return ResourceManager.GetString("sn_nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///NLAARE1~~~N,NL,AAR,E1~~~,N,Aaron Cove,M,YU,4,PL,MW,MS,MS,-,EA,EA,EA,GLFL,-,-,PZ,FHP,GL,PZ,FHP,GL
        ///NLABH~~~~~N,NL,ABH,~~~~~,N,Abraham,M,YU,0,-,MW,F,F,-,EA,AN,UD,TILL,-,-,BR,DYB,GLE,BR,DYB,GLE
        ///NLABNE1~~~N,NL,ABN,E1~~~,N,Alderburn,M,YN,0,-,W,MS,MS,-,EA,EA,EA,TILL,-,-,PZ,HFP,O,PZ,HFP,O
        ///NLABNE2~~~N,NL, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_nl {
            get {
                return ResourceManager.GetString("sn_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///NSACA4~~~~A,NS,ACA,4~~~~,A,Acadia,M,YB,0,-,MW,MF,-,-,EA,-,-,MARI,-,-,RG,GL,GL,RG,RG,GL
        ///NSACA5~~~~A,NS,ACA,5~~~~,A,Acadia,M,YB,0,-,I,MF,-,-,EA,-,-,MARI,-,-,RG,GL,GL,RG,RG,GL
        ///NSACA6~~~~A,NS,ACA,6~~~~,A,Acadia,M,YB,0,-,P,MF,-,-,EA,-,-,MARI,-,-,GL,GL,RG,GL,GL,RG
        ///NSACA~~~~~A,NS,ACA,~~~~~,A,Acadia,M,YB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_ns {
            get {
                return ResourceManager.GetString("sn_ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///ONABM~~~~~A,ON,ABM,~~~~~,A,ABRAM,M,YU,0,-,I,MF,-,-,VC,-,-,LACU,-,-,LU,GL,GL,LU,GL,GL
        ///ONABO~~~~~N,ON,ABO,~~~~~,N,ALBERTON,M,YU,0,-,I,MF,-,-,AN,-,-,FLUV,-,-,RG,HR,GL,RG,HR,GL
        ///ONACE~~~~~A,ON,ACE,~~~~~,A,ANCASTER,M,YU,0,-,W,MF,-,-,VC,-,-,TILL,-,-,BR,MB,E,BR,MB,E
        ///ONAHGSH~~~A,ON,AHG,SH~~~,A,ACHIGAN,M,Y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_on {
            get {
                return ResourceManager.GetString("sn_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///PEAND612~~N,PE,AND,612~~,N,Abney Road,U,YB,0,-,VP,,,-,,,-,FOPT,UNDM,-,OR,M,T,OR,M,T
        ///PEAPT~~~~~N,PE,APT,~~~~~,N,Airport,N,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
        ///PEARN611~~N,PE,ARN,611~~,N,Arlington,U,YB,0,-,VP,,-,-,,-,-,SPPT,-,-,OR,F,TY,OR,F,TY
        ///PEARYAB~~~A,PE,ARY,AB~~~,A,Alberry,M,YU,0,-,MW,MC,-,-, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_pe {
            get {
                return ResourceManager.GetString("sn_pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///QCABT50000A,QC,ABT,50000,A,ABITIBI,M,YB,0,-,I,VF,-,-,AN,-,-,GLLC,-,-,GL,LG,O,GL,LG,O
        ///QCAGO33000N,QC,AGO,33000,N,ARAGO,M,NO,7,FP,W,MS,-,-,EA,-,-,TILL,-,-,PZ,HFP,FR,PZ,HFP,FR
        ///QCAGR30000A,QC,AGR,30000,A,ANGE-GARDIEN,M,YB,3,CT,P,MS,-,-,AN,-,-,TILL,-,-,GL,HG,O,GL,HG,O
        ///QCAHG10000N,QC,AHG,10000,N,ACHIGA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_qc {
            get {
                return ResourceManager.GetString("sn_qc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOIL_ID,PROVINCE,SOIL_CODE,MODIFIER,PROFILE,SOILNAME,KIND,WATERTBL,ROOTRESTRI,RESTR_TYPE,DRAINAGE,PMTEX1,PMTEX2,PMTEX3,PMCHEM1,PMCHEM2,PMCHEM3,MDEP1,MDEP2,MDEP3,ORDER2,G_GROUP2,S_GROUP2,ORDER3,G_GROUP3,S_GROUP3
        ///SKADA43~~~A,SK,ADA,43~~~,A,ARDILL O.BC,M,NO,0,-,W,MF,-,-,VC,-,-,TILL,-,-,CH,B,O,CH,BC,O
        ///SKADA49~~~A,SK,ADA,49~~~,A,ARDILL O.BC,M,NO,0,-,W,MF,-,-,VC,-,-,TILL,-,-,CH,B,O,CH,BC,O
        ///SKADAR43~~A,SK,ADA,R43~~,A,ARDILL O.BC,M,NO,4,LI,W,MF,VF,-,VC,AN,-,TILL,RESD,-,CH,B,O,CH,BC,O
        ///SKADAR49~~A,SK,ADA,R49~~,A, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sn_sk {
            get {
                return ResourceManager.GetString("sn_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,Feed,AAFCO#,AFFCO 2010,IFN #,DM (%),CP (%DM),Crude Fiber (%DM),&quot;Ether extract (EE, %DM)&quot;,&quot;Acid ether extract (AEE, %DM)&quot;,Ash (%DM),GE (kcal/kg),DE (kcal/kg),ME (kcal/kg),NE (kcal/kg),Lactose (%DM),Sucrose (%DM),Raffinose (%DM),Stachyose (%DM),Verbascose (%DM),Oligosaccharides (%DM),Starch (%DM),&quot;Neutral detergent fiber (NDF, %DM)&quot;,&quot;Acid detergent fiber (ADF, %DM)&quot;,Hemicellulose (%DM),&quot;Acid detergent Lignin (ADL, %DM)&quot;,&quot;Total dietary fiber (TDF, %DM)&quot;,&quot;Insoluble dietary fiber (IDF, %DM)&quot;,&quot;Soluble dietary f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Swine_Feed_Ingredient_List {
            get {
                return ResourceManager.GetString("Swine_Feed_Ingredient_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecozone,Texture,TillagePracticeChange,k,LumCKMax
        ///Boreal Shield West,Coarse,IntenseToReduced,0.0262,143
        ///Boreal Shield West,Coarse,ReducedToNone,0.0284,441
        ///Boreal Shield West,Coarse,IntenseToNone,0.0306,584
        ///Boreal Shield West,Coarse,ReducedToIntense,0.0262,-143
        ///Boreal Shield West,Coarse,NoneToReduced,0.0284,-441
        ///Boreal Shield West,Coarse,NoneToIntense,0.0306,-584
        ///Boreal Shield West,Medium,IntenseToReduced,0.0253,217
        ///Boreal Shield West,Medium,ReducedToNone,0.0282,478
        ///Boreal Shield West,Medium,IntenseT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_1 {
            get {
                return ResourceManager.GetString("Table_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province,SoilType,NStubble,NFallow, NMineralizedStubbleFallow
        ///Alberta,Black/Gray Chernozem,61,21, 40
        ///Saskatchewan,Black/Gray Chernozem,77,41,36
        ///Manitoba,Black/Gray Chernozem,90,17,73
        ///Alberta,Brown Chernozem,51,17,34
        ///Saskatchewan,Brown Chernozem,54,21,33
        ///Manitoba,Brown Chernozem,90,17,73
        ///Alberta,Dark Brown Chernozem,47,14,33
        ///Saskatchewan,Dark Brown Chernozem,45,7,38
        ///Manitoba,Dark Brown Chernozem,90,17,73
        ///.
        /// </summary>
        public static string Table_10 {
            get {
                return ResourceManager.GetString("Table_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimalType,Housing,CA
        ///Beef,Confined No Barn,0
        ///Beef,Housed In Barn,0
        ///Beef,Enclosed Pasture,0.17
        ///Beef,Open Range Or Hills,0.36
        ///Dairy,Tie-Stall,0
        ///Dairy,Small Free-Stall,0
        ///Dairy,Large Free-Stall,0
        ///Dairy,Drylot,0
        ///Dairy,Grazing &lt; 3km/d,0.17
        ///Dairy,Grazing &gt; 3km/d,0.3
        ///Sheep,Confined,0.0067
        ///Sheep,Flat Pasture,0.0107
        ///Sheep,Hilly Pasture / Open Range,0.024
        ///.
        /// </summary>
        public static string Table_11_16_26 {
            get {
                return ResourceManager.GetString("Table_11_16_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimalType,DietType,TDN,CP,YM
        ///DairyLactating,Low Energy,66,0.16,0.065
        ///DairyLactating,Medium Energy,71,0.17,0.06
        ///DairyLactating,High Energy,76,0.18,0.058
        ///DairyDry,Far Off Dry,54,0.12,0.065
        ///DairyDry,Close Up,63,0.14,0.065
        ///DairyHeifers,Low Energy,63,0.14,0.065
        ///DairyHeifers,Medium Energy,68,0.18,0.065
        ///DairyBulls,Low Energy,63,0.14,0.065
        ///DairyBulls,Medium Energy,68,0.18,0.065
        ///BeefFinisher,Barley,81,0.125,0.04
        ///BeefFinisher,Corn,83,0.125,0.03
        ///Backgrounder,Medium Growth,70,0.135,0.065
        ///Backgrounder,Slow [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_12_17_30 {
            get {
                return ResourceManager.GetString("Table_12_17_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additive,YMDeductionPercentage
        ///None,0
        ///2% Fat,10
        ///4% Fat,20
        ///Custom,0
        ///.
        /// </summary>
        public static string Table_13_18 {
            get {
                return ResourceManager.GetString("Table_13_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimalType,HandlingSystemName,MCF,EFDirect,FractionalVolatilization
        ///Beef,Compost Intensive,0.005,0.1,0.45
        ///Beef,Compost Passive,0.005,0.01,0.45
        ///Beef,Deep Bedding,0.17,0.01,0.3
        ///Beef,Pasture,0.01,0.02,0.2
        ///Beef,Solid Storage,0.02,0.005,0.45
        ///Dairy,Anaerobic Digester,0.01,0,0.4
        ///Dairy,Compost Intensive,0.005,0.1,0.3
        ///Dairy,Compost Passive,0.005,0.01,0.3
        ///Dairy,Deep Bedding,0.17,0.01,0.3
        ///Dairy,Liquid No Crust,0.17,0,0.4
        ///Dairy,Liquid Crust,0.283,0.005,0.4
        ///Dairy,Pasture,0.01,0.02,0.2
        ///Dairy,Solid Storage,0. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_14_19_23 {
            get {
                return ResourceManager.GetString("Table_14_19_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecozone,Texture,FallowPracticeChange,LumCMax,k
        ///Boreal Shield West,Coarse,FallowCroppingToContinous,1314,0.0305
        ///Boreal Shield West,Coarse,ContinousToFallowCropping,-1314,0.0305
        ///Boreal Shield West,Medium,FallowCroppingToContinous,1314,0.0305
        ///Boreal Shield West,Medium,ContinousToFallowCropping,-1314,0.0305
        ///Boreal Shield West,Fine,FallowCroppingToContinous,1314,0.0305
        ///Boreal Shield West,Fine,ContinousToFallowCropping,-1314,0.0305
        ///Atlantic Maritimes,Coarse,FallowCroppingToContinous,1314,0.0305
        ///Atlantic M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_2 {
            get {
                return ResourceManager.GetString("Table_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Type,Province,VS Excretion (kg VS kg-1 Feed as Fed)
        ///Boar,British Columbia,0.1227,
        ///Starter,British Columbia,0.1446,
        ///Grower,British Columbia,0.1391,
        ///SwineFinisher,British Columbia,0.1391,
        ///Dry Sow,British Columbia,0.1227,
        ///Lactating Sow,British Columbia,0.1227,
        ///Boar,Alberta,0.1228,
        ///Starter,Alberta,0.1504,
        ///Grower,Alberta,0.1389,
        ///SwineFinisher,Alberta,0.1389,
        ///Dry Sow,Alberta,0.1228,
        ///Lactating Sow,Alberta,0.1228,
        ///Boar,Saskatchewan,0.1321,
        ///Starter,Saskatchewan,0.1292,
        ///Grower,Saskatchewan,0.153 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_20 {
            get {
                return ResourceManager.GetString("Table_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet,VS Adjustment (kg kg-1),N Excreted Adjustment (kg kg-1)
        ///Standard,1,1
        ///Reduced Protein,0.99,0.7
        ///Highly Digestible Feed,0.95,0.95
        ///.
        /// </summary>
        public static string Table_21 {
            get {
                return ResourceManager.GetString("Table_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Type,Province,Crude Protein (kg Protein kg-1 Feed As Fed),Feed Intake (kg Head -1 Day-1)
        ///Boar,Alberta,0.145,2.55
        ///Dry Sow,Alberta,0.145,2.55
        ///SwineFinisher,Alberta,0.155,3
        ///Grower,Alberta,0.18,2
        ///Lactating Sow,Alberta,0.2,6.11
        ///Starter,Alberta,0.22,0.7
        ///Boar,British Columbia,0.145,2.55
        ///Dry Sow,British Columbia,0.145,2.55
        ///SwineFinisher,British Columbia,0.155,3
        ///Grower,British Columbia,0.18,2
        ///Lactating Sow,British Columbia,0.2,6.11
        ///Starter,British Columbia,0.22,0.7
        ///Boar,Manitoba,0.145,2.55
        ///Dry S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_22_24 {
            get {
                return ResourceManager.GetString("Table_22_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecozone,Texture,PerennialCroppingChange,LumCMax,k
        ///Boreal Shield West,Coarse,IncreaseInPerennialCroppingArea,1942,0.035
        ///Boreal Shield West,Coarse,DecreaseInPerennialCroppingArea,-1942,0.035
        ///Boreal Shield West,Medium,IncreaseInPerennialCroppingArea,2757,0.0253
        ///Boreal Shield West,Medium,DecreaseInPerennialCroppingArea,-2757,0.0253
        ///Boreal Shield West,Fine,IncreaseInPerennialCroppingArea,3532,0.0218
        ///Boreal Shield West,Fine,DecreaseInPerennialCroppingArea,-3532,0.0218
        ///Atlantic Maritimes,Coarse,IncreaseInPe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_3 {
            get {
                return ResourceManager.GetString("Table_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep Class, Cf (MJ d-1 kg-1), a (MJ kg-1), b (MJ kg-2), Initial Weight (kg), Final Weight (kg), Wool Production (kg year-1)
        ///Ewe,0.217,2.1,0.45,70,70,4
        ///Ram,0.25,2.5,0.35,125,125,4
        ///Weaned Lambs,0.236,3.25,0.385,30,50,0
        ///.
        /// </summary>
        public static string Table_30 {
            get {
                return ResourceManager.GetString("Table_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species,BrownChernozemA,BrownChernozemB,DarkBrownA,DarkBrownB,BlackChernozemA,BlackChernozemB,PlantingSPace
        ///Caragana,0.4017,0.6446,0.4511,0.6446,0.5987,0.6446,10
        ///Colorado Spruce,0.8193,0.456,0.995,0.456,1.0394,0.456,3.5
        ///Green Ash,0.5218,0.2932,0.7284,0.2932,1.1391,0.2932,2.5
        ///Manitoba Maple,0.0916,1.0568,0.0654,1.0568,0.1177,1.0568,2.5
        ///Poplar,0.2089,0.9651,0.3232,0.9651,0.7679,0.9651,2.5
        ///Scots Pine,0.2266,0.6716,0.2895,0.6716,0.3159,0.6716,3.5
        ///Siberian Elm,1.6595,0.2551,2.0672,0.2551,2.6801,0.2551,2.5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_33 {
            get {
                return ResourceManager.GetString("Table_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province,Soil Type,Current Tillage System,Crop Type,EFuel  (GJ ha-1),EHerbicide (GJ ha-1)
        ///Alberta,Black,Intensive,Fallow,2.35,0.06
        ///Alberta,Black,Reduced,Fallow,1.71,0.11
        ///Alberta,Black,Intensive,All,2.63,0.16
        ///Alberta,Black,Reduced,All,2.39,0.23
        ///Alberta,Black,No-till,All,1.43,0.46
        ///Alberta,Black,No-till,Fallow,0.93,0.6
        ///Alberta,Brown,Intensive,Fallow,1.62,0
        ///Alberta,Brown,Reduced,Fallow,1.16,0.07
        ///Alberta,Brown,Intensive,All,2.02,0.16
        ///Alberta,Brown,Reduced,All,1.78,0.23
        ///Alberta,Brown,No-till,All,1.42,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_38 {
            get {
                return ResourceManager.GetString("Table_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeSpecies,a,b,MinDiameter,MaxDiameter,MinHeight,MaxHeight,MinAge,MaxAge,MinSpacing,MaxSpacing,MinMortality,MaxMortality
        ///HybridPoplar,0.09142,2.3011,13.6,59,8.8,23.5,13,60,0.5,10,0,25
        ///WhiteSpruce,0.0066,3.1832,1.3,38,1.9,21.5,6,76,0.5,4,0,66
        ///ScotsPine,0.43264,1.887,17.5,63,6.9,16.7,15,74,1,3.2,0,50
        ///ManitobaMaple,0.29428,1.898,3.2,43.6,2.9,15.2,5,100,1,5,0,47
        ///GreenAsh,0.20637,2.1217,10.9,37,4.1,14.2,12,79,1,5,0,68
        ///Caragana,0.0284,2.576,5.3,24.2,2.5,13.6,7,43,0.4,2.4,0,29
        ///.
        /// </summary>
        public static string Table_5 {
            get {
                return ResourceManager.GetString("Table_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CropType,Province,SoilType,NApplicationRate(kgNha^-1),PApplicationRate(kgPha^-1)
        ///Barley,British Columbia,All,78,40
        ///Barley,Manitoba,All,81,40
        ///Barley,New Brunswick,All,70,40
        ///Barley,Newfoundland and Labrador,All,70,40
        ///Barley,Nova Scotia,All,70,40
        ///Barley,Ontario,All,53,40
        ///Barley,Prince Edward Island,All,55,40
        ///Barley,Quebec,All,49,40
        ///Barley silage,British Columbia,All,80,40
        ///Barley silage,Manitoba,All,80,40
        ///Barley silage,New Brunswick,All,80,40
        ///Barley silage,Newfoundland and Labrador,All,80,40
        ///Barley [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_6 {
            get {
                return ResourceManager.GetString("Table_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CropType,MoistureContent,AGRNConc,BGRNConc,YieldRatio,AGRRatio,BGRRatio,Yield
        ///Barley,0.12,0.007,0.01,0.38,0.47,0.15,1268
        ///Barley silage,0.55,0.007,0.01,0.72,0.13,0.15,2000
        ///Buckwheat,0.12,0.006,0.01,0.24,0.56,0.2,618
        ///Canary seed,0.12,0.007,0.01,0.2,0.6,0.2,445
        ///Canola,0.09,0.008,0.01,0.26,0.6,0.15,748
        ///Chickpeas,0.13,0.018,0.01,0.29,0.51,0.2,520
        ///Coloured/white faba beans,0.13,0.01,0.01,0.46,0.34,0.2,975
        ///Dry peas,0.13,0.018,0.01,0.29,0.51,0.2,943
        ///Durum,0.12,0.006,0.01,0.34,0.51,0.15,1333
        ///Flax,0.08,0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_7 {
            get {
                return ResourceManager.GetString("Table_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecozone,Texture,LItR,KItR,LRtN,KRtN,LItN,KItN,LRtI,KRtI,LNtR,KNtR,LNtI,KNtI,LDF,KDF,LIF,KIF,LIP,KIP,LDP,KDP
        ///Atlantic Maritimes,Medium,246,0.0227,241,0.0219,486,0.0211,-246,0.0227,-241,0.0219,-486,0.0211,1314,0.0305,-1314,0.0305,4813,0.019,-4813,0.019
        ///Boreal Plains,Medium,233,0.0219,464,0.0238,698,0.0258,-233,0.0219,-464,0.0238,-698,0.0258,1314,0.0305,-1314,0.0305,3241,0.0216,-3241,0.0216
        ///Boreal Shield East,Medium,238,0.0266,311,0.023,549,0.0193,-238,0.0266,-311,0.023,-549,0.0193,1314,0.0305,-1314,0.0305, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_7_8_9 {
            get {
                return ResourceManager.GetString("Table_7_8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvinceID,PresentTillage,RFTill
        ///Alberta,No-till,0.8
        ///Alberta,Reduced,0.8
        ///Alberta,Intensive,1
        ///British Columbia,No-till,1
        ///British Columbia,Reduced,1
        ///British Columbia,Intensive,1
        ///Manitoba,No-till,0.8
        ///Manitoba,Reduced,0.8
        ///Manitoba,Intensive,1
        ///New Brunswick,No-till,1.1
        ///New Brunswick,Reduced,1.1
        ///New Brunswick,Intensive,1
        ///Newfoundland and Labrador,No-till,1.1
        ///Newfoundland and Labrador,Reduced,1.1
        ///Newfoundland and Labrador,Intensive,1
        ///Nova Scotia,No-till,1.1
        ///Nova Scotia,Reduced,1.1
        ///Nova Scotia,Int [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_8 {
            get {
                return ResourceManager.GetString("Table_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvinceID,EcodistrictTextureID,RFTexture
        ///Alberta,Fine,1
        ///Alberta,Medium,1
        ///Alberta,Coarse,1
        ///British Columbia,Fine,1
        ///British Columbia,Medium,1
        ///British Columbia,Coarse,1
        ///Manitoba,Fine,1
        ///Manitoba,Medium,1
        ///Manitoba,Coarse,1
        ///New Brunswick,Fine,1.2
        ///New Brunswick,Medium,0.8
        ///New Brunswick,Coarse,0.8
        ///Newfoundland and Labrador,Fine,1.2
        ///Newfoundland and Labrador,Medium,0.8
        ///Newfoundland and Labrador,Coarse,0.8
        ///Nova Scotia,Fine,1.2
        ///Nova Scotia,Medium,0.8
        ///Nova Scotia,Coarse,0.8
        ///Ontario,Fine,1.2
        ///Ontario [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table_9 {
            get {
                return ResourceManager.GetString("Table_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Z,Cluster,Mortality_pct,Year,Age,Stems,DBH_cm,Height_m,Kg_pertree,km_per_ha,Stems_tosum1ha,Biomass_Mgkm,Volume_m3km,Roots_Mgkm,Fineroots_Mgkm
        ///BLK_,BLK_1,15,2073,58,541,35.33924103,16.43406487,560.0194702,1.497544028,748.7720139,202.3116025,240.7484049,22.96962561,10.33633152
        ///BLK_,BLK_1,15,2074,59,541,35.57034302,16.53334999,571.7608032,1.497544028,748.7720139,206.5532577,244.7723625,22.81210979,10.26544941
        ///BLK_,BLK_1,15,2075,60,541,35.81144714,16.63687706,584.1889648,1.497544028,748.7720139,211.0430 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string white_spruce__31_allclusters_future {
            get {
                return ResourceManager.GetString("white_spruce__31_allclusters_future", resourceCulture);
            }
        }
    }
}
