namespace H.Data.Core.Enumerations
{
    public enum CsvResourceNames
    {
        EcodistrictToEcozoneMapping,
        CanSisEcodistrictNamesTable, 
        CanSisPolygonAttributeTable,
        CanSisSoilNameTableAlberta,
        CanSisSoilNameTableBritishColumbia,
        CanSisSoilNameTableManitoba,
        CanSisSoilNameTableNewBrunswick,
        CanSisSoilNameTableNewfoundland,
        CanSisSoilNameTableNovaScotia,
        CanSisSoilNameTableOntario,
        CanSisSoilNameTablePrinceEdwardIsland,
        CanSisSoilNameTableQuebec,
        CanSisSoilNameTableSaskatchewan,
        CanSisComponentTable,
        CanSisSoilLayerTableAlberta,
        CanSisSoilLayerTableBritishColumbia,
        CanSisSoilLayerTableManitoba,
        CanSisSoilLayerTableNewBrunswick,
        CanSisSoilLayerTableNewfoundland,
        CanSisSoilLayerTableNovaScotia,
        CanSisSoilLayerTableOntario,
        CanSisSoilLayerTablePrinceEdwardIsland,
        CanSisSoilLayerTableQuebec,
        CanSisSoilLayerTableSaskatchewan
    }
}
