//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Core.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Core.Test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1985,1,-12.5,0,0
        ///1985,2,0,0,0
        ///1985,3,2,0,0
        ///1985,4,2,0,0
        ///1985,5,6.8,0,0
        ///1985,6,0.3,0,0
        ///1985,7,-6.8,0,0
        ///1985,8,-10,0,0
        ///1985,9,-10.8,0,0
        ///1985,10,-14.8,0,0
        ///1985,11,-6.8,0,0
        ///1985,12,2.5,0,0
        ///1985,13,-1.3,0,0
        ///1985,14,0.3,1,0
        ///1985,15,2,0,0
        ///1985,16,1.3,0,0
        ///1985,17,7,0,0
        ///1985,18,-2.8,3.5,0
        ///1985,19,-14.3,4.5,0
        ///1985,20,-16.8,0,0
        ///1985,21,-13,0,0
        ///1985,22,-6.8,0,0
        ///1985,23,-2,0,0
        ///1985,24,2.8,0,0
        ///1985,25,1.3,0,0
        ///1985,26,-4.3,0,0
        ///1985,27,-5.3,0.3,0
        ///1985,28,-5,3.3,0
        ///1985,29,-21.3,0,0
        ///1985,30,-23,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string climate_parameter_tool_input {
            get {
                return ResourceManager.GetString("climate_parameter_tool_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year,Julian day,Mean Daily Air Temperature,Mean Daily Precipitation,Mean Daily PET
        ///1912,1,-15.6,0,0
        ///1912,2,-17.5,2,0
        ///1912,3,-17.2,0,0
        ///1912,4,-15.3,0,0
        ///1912,5,-20.8,2.5,0
        ///1912,6,-24.2,0,0
        ///1912,7,-18.4,0.8,0
        ///1912,8,-13.1,0,0
        ///1912,9,-22.2,0.8,0
        ///1912,10,-30.3,0.5,0
        ///1912,11,-30,0,0
        ///1912,12,-11.7,0,0
        ///1912,13,-10,0,0
        ///1912,14,-16.7,0,0
        ///1912,15,-1.2,0,0
        ///1912,16,0.6,8.6,0
        ///1912,17,-9.4,0,0
        ///1912,18,-19.7,0,0
        ///1912,19,-12,0,0
        ///1912,20,-2.5,0,0
        ///1912,21,4.8,0,0
        ///1912,22,2.2,0,0
        ///1912,23,-3.3,0,0
        ///1912,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string custom_climate_data {
            get {
                return ResourceManager.GetString("custom_climate_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter,Year,tfac,wfac,CI,Sand,LC,NC,Beta,alpha,kA,ACTIVEy*,ACTIVEy,Active_diff,kS,SLOWy*,SLOWy,Slow_diff,kP,PASSIVEy*,PASSIVEy,Passive_diff,SOCy,SOC_diff
        ///1,1970,0.467,1.053,3.569,0.25,0.111,0.021,2.694,1.80,4.829,0.37,0.37,0.03,0.312,3.90,3.70,0.09,0.0034,63.61,58.82,0.02,62.89,0.14
        ///2,1971,0.489,1.322,3.718,0.25,0.111,0.021,2.807,1.88,6.351,0.30,0.30,-0.08,0.410,3.09,3.45,-0.25,0.0045,50.39,58.78,-0.04,62.52,-0.36
        ///3,1972,0.492,0.913,3.096,0.25,0.111,0.021,2.337,1.56,4.417,0.35,0.35,0.06,0.285,3.70,3.52, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outputs {
            get {
                return ResourceManager.GetString("outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year,Month,YearMonth,AvgTAvg,SumRain,SumEvap,Ti,mappeti,Wi,,Row Labels,AvgAnnTi,AvgAnnWi,,,Year,tfac,wfac
        ///1950,1,1950,20.7,2.8,253.8,0.712,0.011,0.228,,1950,0.520,0.653,,,1950,0.520,0.980
        ///1950,2,1950.083,20.7,34.4,214.4,0.712,0.16,0.42,,1951,0.521,0.829,,,1951,0.521,1.244
        ///1950,3,1950.167,18.6,10.7,176.6,0.631,0.061,0.293,,1952,0.479,0.827,,,1952,0.479,1.241
        ///1950,4,1950.25,16.6,12.9,104.2,0.551,0.124,0.374,,1953,0.508,0.789,,,1953,0.508,1.183
        ///1950,5,1950.333,13.8,130.1,62.8,0.443,1.25,1.5,,1954,0.504,0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tier2TestData {
            get {
                return ResourceManager.GetString("Tier2TestData", resourceCulture);
            }
        }
    }
}
