using System;
using System.Diagnostics;
using H.Core.Enumerations;
using H.Core.Properties;

namespace H.Core.Converters
{
    public class CropTypeStringConverter : ConverterBase
    {
        public CropType Convert(string input)
        {
            switch (this.GetLettersAsLowerCase(input))
            {
                case "alfalfaseed":
                    return CropType.AlfalfaSeed;
                case "barley":
                    return CropType.Barley;
                case "barleysilage":
                    return CropType.BarleySilage;
                case "barleysilageunderseed":
                    return CropType.BarleySilageUnderSeed;
                case "bromehay":
                    return CropType.BromeHay;
                case "grasssilage":
                    return CropType.GrassSilage;
                case "beans":
                    return CropType.Beans;
                case "beansdryfield":
                case "dryfieldbeans":
                    return CropType.BeansDryField;
                case "otherdryfieldbeans":
                    return CropType.OtherDryFieldBeans;
                case "berriesgrapes":
                    return CropType.BerriesAndGrapes;
                case "buckwheat":
                    return CropType.Buckwheat;
                case "canaryseed":
                case "canaryseeds":
                    return CropType.CanarySeed;
                case "canola":
                    return CropType.Canola;
                case "caraway":
                    return CropType.Caraway;
                case "carrot":
                    return CropType.Carrot;
                case "chickpeas":
                case "chickpea":
                    return CropType.Chickpeas;
                case "colouredwhitefababeans":
                    return CropType.ColouredWhiteFabaBeans;
                case "cpswheat":
                    return CropType.CPSWheat;
                case "drybean":
                    return CropType.DryBean;
                case "drypeas":
                case "drypea":
                case "peasdry":
                    return CropType.DryPeas;
                case "dryfieldpeas":
                    return CropType.DryFieldPeas;
                case "dill":
                    return CropType.Dill;
                case "durum":
                case "wheatdurum":
                case "durumwheat":
                    return CropType.Durum;
                case "fababean":
                    return CropType.FabaBeans;
                case "fallow":
                    return CropType.Fallow;
                case "fallrye":
                case "ryefallremaining":
                    return CropType.FallRye;
                case "fieldpea":
                    return CropType.FieldPeas;
                case "flaxseed":
                    return CropType.FlaxSeed;
                case "freshcornsweet":
                    return CropType.FreshCornSweet;
                case "freshpeas":
                    return CropType.FreshPeas;
                case "forage":
                    return CropType.Forage;
                case "foddercorn":
                    return CropType.FodderCorn;
                case "forageforseed":
                    return CropType.ForageForSeed;
                case "graincorn":
                case "cornforgrain":
                    return CropType.GrainCorn;
                case "grains":
                    return CropType.Grains;
                case "genericgrains":
                    return CropType.GenericGrains;
                case "corn":
                case "maize":
                    return CropType.Corn;
                case "grainsorghum":
                    return CropType.GrainSorghum;
                case "grassseed":
                    return CropType.GrassSeed;
                case "rangelandlandnative":
                    return CropType.RangelandNative;
                case "greenfeed":
                    return CropType.GreenFeed;
                case "hardredspringwheat":
                    return CropType.HardRedSpringWheat;
                case "tamegrass":
                    return CropType.TameGrass;
                case "grasshay":
                    return CropType.GrassHay;
                case "tamelegume":
                    return CropType.TameLegume;
                case "nonlegumehay":
                    return CropType.NonLegumeHay;
                case "tamemixed":
                case "mixedhay":
                    return CropType.TameMixed;
                case "hayandforageseed":
                    return CropType.HayAndForageSeed;
                case "hairyvetch":
                    return CropType.HairyVetch;
                case "hairyvetchrye":
                    return CropType.HairyVetchAndRye;
                case "hyola":
                    return CropType.Hyola;
                case "lentils":
                case "lentil":
                    return CropType.Lentils;
                case "linola":
                    return CropType.Linola;
                case "maltbarley":
                    return CropType.MaltBarley;
                case "marketgarden":
                    return CropType.MarketGarden;
                case "milkvetch":
                    return CropType.MilkVetch;
                case "millet":
                    return CropType.Millet;
                case "mint":
                    return CropType.Mint;
                case "mixedgrains":
                case "mixedgrain":
                    return CropType.MixedGrains;
                case "mustard":
                    return CropType.Mustard;
                case "mustardseed":
                    return CropType.MustardSeed;
                case "monarda":
                    return CropType.Monarda;
                case "nativepasture":
                    return CropType.NativePasture;
                case "oats":
                    return CropType.Oats;
                case "oatsilage":
                    return CropType.OatSilage;
                case "oilseeds":
                    return CropType.Oilseeds;
                case "onion":
                    return CropType.Onion;
                case "otherfieldcrops":
                    return CropType.OtherFieldCrops;
                case "peas":
                    return CropType.Peas;
                case "pulses":
                    return CropType.Pulses;
                case "pulsecrops":
                    return CropType.PulseCrops;
                case "seededgrassland":
                    return CropType.SeededGrassland;
                case "peanuts":
                    return CropType.Peanuts;
                case "perennialforages":
                    return CropType.PerennialForages;
                case "perennialgrasses":
                    return CropType.PerennialGrasses;
                case "potatoes":
                case "potatos":
                case "potato":
                    return CropType.Potatoes;
                case "rice":
                    return CropType.Rice;
                case "rye":
                case "ryeall":
                    return CropType.Rye;
                case "safflower":
                    return CropType.Safflower;
                case "seedpotato":
                    return CropType.SeedPotato;
                case "silagecorn":
                case "cornsilage":
                    return CropType.SilageCorn;
                case "smallfruit":
                    return CropType.SmallFruit;
                case "softwheat":
                    return CropType.SoftWheat;
                case "soybeans":
                case "soybean":
                    return CropType.Soybeans;
                case "sorghum":
                    return CropType.Sorghum;
                case "sorghumsudangrass":
                    return CropType.SorghumSudanGrass;
                case "smallgraincereals":
                    return CropType.SmallGrainCereals;
                case "springwheat":
                case "wheatspring":
                    return CropType.SpringWheat;
                case "springrye":
                case "ryespring":
                    return CropType.SpringRye;
                case "sugarbeets":
                    return CropType.SugarBeets;
                case "summerfallow":
                    return CropType.SummerFallow;
                case "sunflower":
                    return CropType.Sunflower;
                case "sunflowerseed":
                case "sunflowerseeds":
                    return CropType.SunflowerSeed;
                case "tamepasture":
                    return CropType.TamePasture;
                case "timothyhay":
                    return CropType.TimothyHay;
                case "tobacco":
                    return CropType.Tobacco;
                case "totaltreefruitsnuts":
                    return CropType.TreeFruitAndNuts;
                case "triticale":
                    return CropType.Triticale;
                case "tubers":
                    return CropType.Tubers;
                case "turfsod":
                    return CropType.TurfSod;
                case "undersownbarley":
                    return CropType.UndersownBarley;
                case "vegetables":
                    return CropType.Vegetables;
                case "wheatbolinder":
                    return CropType.WheatBolinder;
                case "wheatgan":
                    return CropType.WheatGan;
                case "wheat":
                case "wheatall":
                    return CropType.Wheat;
                case "wheatrye":
                    return CropType.WheatRye;
                case "winterwheat":
                case "wheatwinter":
                case "wheatwinterremaining":
                    return CropType.WinterWheat;
                case "winterweeds":
                    return CropType.WinterWeeds;
                case "fieldpeas":
                    return CropType.FieldPeas;
                case "berriesandgrapes":
                    return CropType.BerriesAndGrapes;
                case "flax":
                    return CropType.Flax;
                case "triticalesilage":
                    return CropType.TriticaleSilage;
                case "wheatsilage":
                    return CropType.WheatSilage;
                case "grassclovermixtures":
                    return CropType.GrassCloverMixtures;
                case "redclovertrifoliumpratensel":
                    return CropType.RedCloverTrifoliumPratenseL;
                case "berseemclovertrifoliumalexandriuml":
                    return CropType.BerseemCloverTrifoliumAlexandriumL;
                case "sweetclovermelilotusofficinalis":
                    return CropType.SweetCloverMelilotusOfficinalis;
                case "crimsonclovertrifoliumincarnatum":
                    return CropType.CrimsonCloverTrifoliumIncarnatum;
                case "hairyvetchviciavillosaroth":
                    return CropType.HairyVetchViciaVillosaRoth;
                case "alfalfamedicagosatival":
                    return CropType.AlfalfaMedicagoSativaL;
                case "fababeanbroadbeanviciafaba":
                    return CropType.FabaBeanBroadBeanViciaFaba;
                case "cowpeavignaunguiculata":
                    return CropType.CowpeaVignaUnguiculata;
                case "austrianwinterpea":
                    return CropType.AustrianWinterPea;
                case "rapeseedbrassicanapusl":
                    return CropType.RapeseedBrassicaNapusL;
                case "winterturniprapebrassicarapasppoleiferalcvlargo":
                    return CropType.WinterTurnipRapeBrassicaRapaSppOleiferaLCVLargo;
                case "phaceliaphaceliatanacetifoliacvphaci":
                    return CropType.PhaceliaPhaceliaTanacetifoliaCVPhaci;
                case "forageradishraphanussativusl":
                    return CropType.ForageRadishRaphanusSativusL;
                case "mustardsinapusalbalsubspmaireihlindbmaire":
                    return CropType.MustardSinapusAlbaLSubspMaireiHLindbMaire;
                case "barleyhordeumvulgare":
                    return CropType.BarleyHordeumVulgare;
                case "oatavenasativa":
                    return CropType.OatAvenaSativa;
                case "ryesecalecerealewinterryecerealrye":
                    return CropType.RyeSecaleCerealeWinterRyeCerealRye;
                case "sesamesesamumindicum":
                    return CropType.SesameSesamumIndicum;
                case "flaxlinumusitatissimum":
                    return CropType.FlaxLinumUsitatissimum;
                case "ryegrassloliumperennel":
                    return CropType.RyeGrassLoliumPerenneL;
                case "annualryegrassloliummultiflorum":
                    return CropType.AnnualRyeGrassLoliumMultiflorum;
                case "sorghumsorghumbicolour":
                    return CropType.SorghumSorghumBicolour;
                case "pigeonbean":
                    return CropType.PigeonBean;
                case "shepherdspurse":
                    return CropType.ShepherdsPurse;
                case "winterwheattriticumaestivum":
                    return CropType.WinterWheatTriticumAestivum;
                case "feedbarley":
                    return CropType.FeedBarley;
                case "redlentil":
                    return CropType.RedLentils;
                case "millingoats":
                    return CropType.MillingOats;
                case "polishcanola":
                    return CropType.PolishCanola;
                case "argentinehtcanola":
                    return CropType.ArgentineHTCanola;
                case "kabulichickpea":
                    return CropType.KabuliChickpea;
                case "yellowmustard":
                    return CropType.YellowMustard;
                case "cerealsilage":
                    return CropType.CerealSilage;
                case "cereals":
                    return CropType.Cereals;
                case "alfalfahay":
                case "alfalfa":
                    return CropType.AlfalfaHay;
                case "ediblegreenpeas":
                    return CropType.EdibleGreenPeas;
                case "edibleyellowpeas":
                    return CropType.EdibleYellowPeas;
                case "blackbean":
                    return CropType.BlackBean;
                case "hybridfallrye":
                    return CropType.HybridFallRye;
                case "brownmustard":
                    return CropType.BrownMustard;
                case "orientalmustard":
                    return CropType.OrientalMustard;
                case "sunfloweroilseedemss":
                    return CropType.SunflowerOilseedEMSS;
                case "desichickpea":
                    return CropType.DesiChickpeas;
                case "camelina":
                    return CropType.Camelina;
                case "carawayfirstseason":
                    return CropType.CarawayFirstSeason;
                case "carawaysecondseason":
                    return CropType.CarawaySecondSeason;
                case "coriander":
                    return CropType.Coriander;
                case "fenugreek":
                    return CropType.Fenugreek;
                case "quinoa":
                    return CropType.Quinoa;
                case "wheathardredspring":
                    return CropType.WheatHardRedSpring;
                case "wheatprairiespring":
                    return CropType.WheatPrairieSpring;
                case "wheatotherspring":
                    return CropType.WheatOtherSpring;
                case "beanspinto":
                    return CropType.BeansPinto;
                case "sunflowerconfection":
                    return CropType.SunflowerConfection;
                case "largegreenlentils":
                    return CropType.LargeGreenLentils;
                case "wheatnorthernhardred":
                    return CropType.WheatNorthernHardRed;
                case "sunfloweroil":
                    return CropType.SunflowerOil;
                case "beanswhite":
                    return CropType.BeansWhite;
                case "kabulichickpealarge":
                    return CropType.LargeKabuliChickpea;
                case "kabulichickpeasmall":
                    return CropType.SmallKabuliChickpea;
                case "colouredbeans":
                    return CropType.ColouredBeans;
                case "hardredwinterwheat":
                    return CropType.HardRedWinterWheat;
                case "northernontariobarley":
                    return CropType.NorthernOntarioBarley;
                case "southernontariobarley":
                    return CropType.SouthernOntarioBarley;
                case "northernontariooats":
                    return CropType.NorthernOntarioOats;
                case "rangelandnative":
                    return CropType.RangelandNative;
                case "southernontariooats":
                    return CropType.SouthernOntarioOats;
                case "springcanolaht":
                    return CropType.SpringCanolaHt;
                case "soybeansnotill":
                    return CropType.SoybeanNoTill;
                case "soybeansroundupready":
                    return CropType.SoybeansRoundUpReady;
                case "switchgrassdirect":
                    return CropType.SwitchgrassDirect;
                case "switchgrassdirectnotill":
                    return CropType.SwitchgrassDirectNoTill;
                case "switchgrassunderseeded":
                    return CropType.SwitchgrassUnderseeded;
                case "switchgrassunderseedednotill":
                    return CropType.SwitchgrassUnderseededNoTill;
                case "softwinterwheat":
                    return CropType.SoftWinterWheat;
                case "softwinterwheatnotill":
                    return CropType.SoftWinterWheatNoTill;
                case "whiteblackbeans":
                    return CropType.WhiteBlackBeans;
                case "whitebeans":
                    return CropType.WhiteBeans;
                case "wintercanolahybrid":
                    return CropType.WinterCanolaHybrid;
                case "hardredwinterwheatnotillage":
                    return CropType.HardRedWinterWheatNoTill;
                case "nfixingforages":
                    return CropType.NFixingForages;
                case "nonnfixingforages":
                    return CropType.NonNFixingForages;

                default:
                    {
                        Trace.TraceError($"{nameof(CropTypeStringConverter)}: Crop type '{input}' not mapped, returning default value.");

                        return CropType.NotSelected;
                    }
            }
        }
    }
}
