#region Imports

using System;
using System.Windows.Input;
using H.Core.Enumerations;
using H.Core.Properties;

#endregion

namespace H.Core.Converters {
    /// <summary>
    /// </summary>
    public class FeedIngredientStringConverter : ConverterBase {
        #region Public Methods

        public IngredientType Convert(string input)
        {
            input = this.GetLettersAsLowerCase(input);
            switch (input)
            {
                case "alfalfacubes":
                    return IngredientType.AlfalfaCubes;
                case "alfalfadehy":
                    return IngredientType.AlfalfaDehy;
                case "alfalfafresh":
                    return IngredientType.AlfalfaFresh;
                case "alfalfagreenchop":
                    return IngredientType.AlfalfaGreenchop;
                case "alfalfahay":
                    return IngredientType.AlfalfaHay;
                case "alfalfameal":
                    return IngredientType.AlfalfaMeal;
                case "alfalfahaylage":
                    return IngredientType.AlfalfaHaylage;
                case "alfalfamedicagosativacp":
                    return IngredientType.AlfalfaMedicago;
                case "almondhulls":
                    return IngredientType.AlmondHulls;
                case "applepomace":
                    return IngredientType.ApplePomace;
                case "applepomacewet":
                    return IngredientType.ApplePomaceWet;
                case "bakeryproducts":
                    return IngredientType.BakeryProducts;
                case "bakerybiproductbyproductmeal":
                    return IngredientType.BakeryProductMeal;
                case "bakerybiproductbreadmeal":
                    return IngredientType.BakeryBreadMeal;
                case "bakerybiproductcerealbyproduct":
                    return IngredientType.BakeryCerealByProduct;
                case "bakerybiproductcookiebyproduct":
                    return IngredientType.BakeryCookieByProduct;
                case "bakerymeal":
                    return IngredientType.BakeryMeal;
                case "barley":
                    return IngredientType.Barley;
                case "barleydistillersdriedgrainswithsolubles":
                    return IngredientType.BarleyDistillerDriedGrainsWithSolubles;
                case "barleygrain":
                    return IngredientType.BarleyGrain;
                case "barleygrainflaked":
                    return IngredientType.BarleyGrainFlaked;
                case "barleygrainrolled":
                    return IngredientType.BarleyGrainRolled;
                case "barleymaltsprouts":
                    return IngredientType.BarleyMaltSprouts;
                case "barleyhay":
                    return IngredientType.BarleyHay;
                case "barleyhulless":
                    return IngredientType.BarleyHulless;
                case "barleysilage":
                    return IngredientType.BarleySilage;
                case "barleysilageheaded":
                    return IngredientType.BarleySilageHeaded;
                case "barleystraw":
                    return IngredientType.BarleyStraw;
                case "beansfaba":
                    return IngredientType.FabaBeans;
                case "beansphaseolusspp":
                    return IngredientType.BeansPhaseolusSPP;
                case "beetpulpdry":
                    return IngredientType.BeetPulpDry;
                case "beetsugarpulpdried":
                    return IngredientType.BeetSugarPulpDried;
                case "beetpulpwet":
                    return IngredientType.BeetPulpWet;
                case "bermudagrasscynodondactlyoncoastalhayearlyhead":
                    return IngredientType.BermudaGrassCoastalHayEarlyHead;
                case "bermudagrasscynodondactlyontiftonhaywkgrowth":
                    return IngredientType.BermudaGrassCoastalHayEarlyHead;
                case "bermudagrassfresh":
                    return IngredientType.BermudaGrassFresh;
                case "bermudagrasshay":
                    return IngredientType.BermudaGrassHay;
                case "bermudagrasssilage":
                    return IngredientType.BermudaGrassSilage;
                case "bloodcells":
                    return IngredientType.BloodCells;
                case "bloodcellsspraydried":
                    return IngredientType.BloodCellsSprayDried;
                case "bloodmeal":
                    return IngredientType.BloodMeal;
                case "bloodmealringdried":
                    return IngredientType.BloodMealRingDried;
                case "bloodplasma":
                    return IngredientType.BloodPlasma;
                case "bloodplasmaspraydried":
                    return IngredientType.BloodPlasmaSprayDried;
                case "bloodmealbatchdriedcompositiondatafromringdried":
                    return IngredientType.BloodMealBatchDried;
                case "bluegrasshay":
                    return IngredientType.BlueGrassHay;
                case "bluestemfresh":
                    return IngredientType.BlueStemFresh;
                case "bluestemhay":
                    return IngredientType.BlueStemHay;
                case "brewersdriedgrains":
                    return IngredientType.BrewersDriedGrains;
                case "brewersgrains":
                    return IngredientType.BrewersGrains;
                case "brewersgrainsdried":
                    return IngredientType.BrewersDriedGrains;
                case "brewersgrainswet":
                    return IngredientType.BrewersWetGrains;
                case "brewerswetgrains":
                    return IngredientType.BrewersWetGrains;
                case "brewersyeastwet":
                    return IngredientType.BrewersYeastWet;
                case "bromegrasshay":
                    return IngredientType.BromeGrassHay;
                case "bromegrasssilage":
                    return IngredientType.BromeGrassSilage;
                case "buffalograss":
                    return IngredientType.BuffaloGrass;
                case "camelinameal":
                    return IngredientType.CamelinaMeal;
                case "camelinamealmech":
                    return IngredientType.CamelinaMealMech;
                case "canefresh":
                    return IngredientType.CaneFresh;
                case "canehay":
                    return IngredientType.CaneHay;
                case "canesilage":
                    return IngredientType.CaneSilage;
                case "canolafullfat":
                    return IngredientType.CanolaFullFat;
                case "canolagrain":
                    return IngredientType.CanolaGrain;
                case "canolameal":
                    return IngredientType.CanolaMeal;
                case "canolamealexpelled":
                    return IngredientType.CanolaMealExpelled;
                case "canolamealsolvent":
                    return IngredientType.CanolaMealSolvent;
                case "canolamealsolventextracted":
                    return IngredientType.CanolaMealSolvent;
                case "canolamealmechextracted":
                    return IngredientType.CanolaMealMechExtracted;
                case "canolaseed":
                    return IngredientType.CanolaSeed;
                case "chickpeas":
                    return IngredientType.ChickPeas;
                case "chocolatebyproduct":
                    return IngredientType.ChocolateByProduct;
                case "casein":
                    return IngredientType.Casein;
                case "cassavameal":
                    return IngredientType.CassavaMeal;
                case "cassavatapiocameal":
                    return IngredientType.CassavaMeal;
                case "citruspulp":
                    return IngredientType.CitrusPulp;
                case "citruspulpdry":
                    return IngredientType.CitrusPulpDry;
                case "citruspulpdried":
                    return IngredientType.CitrusPulpDry;
                case "citruspulpwet":
                    return IngredientType.CitrusPulpWet;
                case "copraexpelled":
                    return IngredientType.CopraExpelled;
                case "coprameal":
                    return IngredientType.CopraMeal;
                case "copramealmechanicalextracted":
                    return IngredientType.CopraMealMech;
                case "copramealsolventextracted":
                    return IngredientType.CopraMealSolvent;
                case "cornbran":
                    return IngredientType.CornBran;
                case "corncobs":
                    return IngredientType.CornCobs;
                case "corndistillersdriedgrains":
                    return IngredientType.CornDistillersDriedGrains;
                case "corndistillersdriedgrainswithsolubles":
                    return IngredientType.CornDistillersDriedGrainsSolubles;
                case "corndistillersdriedgrainswithsolublesgreaterthantenpercentoil":
                    return IngredientType.CornDistillersDriedGrainsSolublesGreaterThanTenPercentOil;
                case "corndistillersdriedgrainswithsolublesgreaterthansixandlessthanninepercentoil":
                    return IngredientType.CornDistillersDriedGrainsSolublesGreaterThanSixAndLessThanNinePercentOil;
                case "corndistillersdriedgrainswithsolubleslessthanfourpercentoil":
                    return IngredientType.CornDistillersDriedGrainsSolublesLessThanFourPercentOil;
                case "cornhpdistillersdriedgrains": //double check this isn't phosphorus instead of protein
                    return IngredientType.CornHpDistillersDriedGrains;
                case "corndistillerssolubles":
                    return IngredientType.CornDistillersSolubles;
                case "corngraindry":
                    return IngredientType.CornGrainDry;
                case "corngerm":
                    return IngredientType.CornGerm;
                case "cornhominyfeed":
                    return IngredientType.CornHominyFeed;
                case "cornearcorn":
                    return IngredientType.CornEarCorn;
                case "cornearlage":
                    return IngredientType.CornEarlage;
                case "corngermmeal":
                    return IngredientType.CornGermMeal;
                case "cornglutenfeed":
                    return IngredientType.CornGlutenFeed;
                case "cornglutenfeedanddistillersgoldensynergy":
                    return IngredientType.CornGlutenFeedAndDistillersGoldenSynergy;
                case "cornglutenfeedwet":
                    return IngredientType.CornGlutenFeedWet;
                case "cornglutenfeedwetsweetbran":
                    return IngredientType.CornGlutenFeedWetSweetBran;
                case "cornglutenfeeddry":
                    return IngredientType.CornGlutenFeedDry;
                case "cornglutenmeal":
                    return IngredientType.CornGlutenMeal;
                case "corngrain":
                    return IngredientType.CornGrain;
                case "corngrainhighmoisture":
                    return IngredientType.CornGrainHighMoisture;
                case "corngrainsteamflaked":
                    return IngredientType.CornGrainSteamFlaked;
                case "corngreenchop":
                    return IngredientType.CornGreenchop;
                case "corngritshominyfeed":
                    return IngredientType.CornGritsHominyFeed;
                case "cornnutridense":
                    return IngredientType.CornNutridense;
                case "cornscreenings":
                    return IngredientType.CornScreenings;
                case "cornsilage":
                    return IngredientType.CornSilage;
                case "cornsnaplage":
                    return IngredientType.BermudaGrassSilage;
                case "cornstalklage":
                    return IngredientType.CornStalklage;
                case "cornstalks":
                    return IngredientType.CornStalks;
                case "cornsteep":
                    return IngredientType.CornSteep;
                case "cornyellowcobs":
                    return IngredientType.CornYellowCobs;
                case "cornyellowdent":
                    return IngredientType.CornYellowDent;
                case "cornyellowdistillersgrainssolublesdried":
                    return IngredientType.CornYellowDistillersGrainSolublesDried;
                case "cornyellowglutenfeeddried":
                    return IngredientType.CornYellowGlutenFeedDried;
                case "cornyellowglutenmealdried":
                    return IngredientType.CornYellowGlutenMealDried;
                case "cornyellowgraingraunddry":
                    return IngredientType.CornYellowGrainGraundDry;
                case "cornyellowgraincrackeddry":
                    return IngredientType.CornYellowGrainCrackedDry;
                case "cornyellowgrainsteamflacked":
                    return IngredientType.CornYellowGrainSteamFlacked;
                case "cornyellowgrainrolledhighmoisture":
                    return IngredientType.CornYellowGrainRolledHighMoisture;
                case "cornyellowgraingroundhighmoisture":
                    return IngredientType.CornYellowGrainGroundHighMoisture;
                case "cornyellowgrainandcobdryground":
                    return IngredientType.CornYellowGrainAndCobDryGround;
                case "cornyellowgrainandcobhighmoistureground":
                    return IngredientType.CornYellowGrainAndCobHighMoistureGround;
                case "cornyellowhominy":
                    return IngredientType.CornYellowHominy;
                case "cornyellowsilageimmaturedm":
                    return IngredientType.CornYellowSilageImmature;
                case "cornyellowsilagenormaldm":
                    return IngredientType.CornYellowSilageNormal;
                case "cornyellowsilagematuredm":
                    return IngredientType.CornYellowSilageMature;
                case "cottonburrs":
                    return IngredientType.CottonBurrs;
                case "cottongintrash":
                    return IngredientType.BermudaGrassSilage;
                case "cottonseed":
                    return IngredientType.CottonSeed;
                case "cottonseedfullfat":
                    return IngredientType.CottonseedFullFat;
                case "cottonseedhulls":
                    return IngredientType.CottonseedHulls;
                case "cottonseedmeal":
                    return IngredientType.CottonseedMeal;
                case "cottonseedmealmechanicalextracted":
                    return IngredientType.CottonSeedMealMech;
                case "cottonseedwhole":
                    return IngredientType.CottonseedWhole;
                case "cottonseedwholeseedwithlint":
                    return IngredientType.CottonSeedWholeWithLint;
                case "cottonseedmealsolventcp":
                    return IngredientType.CottonSeedMealSolvent;
                case "cowpeas":
                    return IngredientType.CowPeas;
                case "distillersgrainplussolubledry":
                    return IngredientType.DistillersGrainPlusSolubleDry;
                case "distillersgrainsplussolublemodified":
                    return IngredientType.DistillersGrainPlusSolubleModified;
                case "distillersgrainsplussolubleswet":
                    return IngredientType.DistillersGrainPlusSolubleWet;
                case "distillerssolubles":
                    return IngredientType.DistillersSolubles;
                case "driedyeast":
                    return IngredientType.DriedYeast;
                case "eggwholespraydried":
                    return IngredientType.EggWholeSprayDried;
                case "fababeans":
                    return IngredientType.FabaBeans;
                case "fatandoilscalciumsoaps":
                    return IngredientType.FatAndOilsCalciumSoaps;
                case "fatandoilshydrolyzedtallowfattyacids":
                    return IngredientType.FatAndOilsHydrolyzedTallowFattyAcids;
                case "fatandoilspartiallyhydrogenatedtallow":
                    return IngredientType.FatAndOilsPartiallyHydrogenatedTallow;
                case "fatandoilstallow":
                    return IngredientType.FatAndOilsTallow;
                case "fatandoilsvegitableoils":
                    return IngredientType.FatAndOilsVegitableOils;
                case "feathermeal":
                    return IngredientType.FeatherMeal;
                case "feathershydrolizedmeal":
                    return IngredientType.FeathersHydrolizedMeal;
                case "feathershydrolizedmealwithsomeviscera":
                    return IngredientType.FeathersHydrolizedMealSomeViscera;
                case "fescuehay":
                    return IngredientType.FescueHay;
                case "fieldpeas":
                    return IngredientType.FieldPeas;
                case "fieldpeashighcp":
                    return IngredientType.FieldPeasHighCP;
                case "fieldpeaslowcp":
                    return IngredientType.FieldPeasLowCP;
                case "fieldpeasplits":
                    return IngredientType.FieldPeaSplits;
                case "fishbyproductsanchovymealmech":
                    return IngredientType.FishByProductsAnchovyMealMech;
                case "fishbyproductsmenhadenmealmech":
                    return IngredientType.FishByProductsMenhadenMealMech;
                case "fishmeal":
                    return IngredientType.FishMeal;
                case "fishmealcombined":
                    return IngredientType.FishMealCombined;
                case "fishmealmechanicalextracted":
                    return IngredientType.FishMealMech;
                case "fishproteinhydrolized":
                    return IngredientType.FishProteinHydrolized;
                case "flaxseed":
                    return IngredientType.Flaxseed;
                case "flaxseedmeal":
                    return IngredientType.FlaxseedMeal;
                case "flaxseedmealmechanicalextracted":
                    return IngredientType.FlaxseedMealMech;
                case "foragesorghumsilage":
                    return IngredientType.ForageSorghamSilage;
                case "foragesorghumsudan":
                    return IngredientType.ForageSorghamSudan;
                case "foragesorghumsudanhay":
                    return IngredientType.ForageSorghamSudanHay;
                case "foragesorghumsudansilage":
                    return IngredientType.ForageSorghamSudanSilage;
                case "foragesorghumfresh":
                    return IngredientType.ForageSorghamFresh;
                case "foragesorghumhay":
                    return IngredientType.ForageSorghamHay;
                case "foxtailmillet":
                    return IngredientType.FoxtailMillet;
                case "freshsoybeanforage":
                    return IngredientType.FreshSoybeanForage;
                case "gelatin":
                    return IngredientType.Gelatin;
                case "glycerin":
                    return IngredientType.ForageGlycerin;
                case "grainsorghumgrain":
                    return IngredientType.ForageGrainSorghumGrain;
                case "grainsorghumhay":
                    return IngredientType.ForageGrainSorghumHay;
                case "grainsorghumsilage":
                    return IngredientType.ForageGrainSorghumSilage;
                case "grainsorghumstalks":
                    return IngredientType.ForageGrainSorghumStalks;
                case "grainsorghumflaked":
                    return IngredientType.CornGrainSteamFlaked;
                case "grainsorghumhighmoisture":
                    return IngredientType.ForageGrainSorghumHighMoisture;
                case "grapepomacedry":
                    return IngredientType.ForageGrapePomaceDry;
                case "grapepomacewet":
                    return IngredientType.ForageGrapePomaceWet;
                case "grassescoolseasonpastureintensivelymanaged":
                    return IngredientType.GrassesCoolPastureIntense;
                case "grassescoolseasonhayallsamples":
                    return IngredientType.GrassesCoolHayAllSamples;
                case "grassescoolseasonhayimmaturendf":
                    return IngredientType.GrassesCoolHayImmature;
                case "grassescoolseasonhaymidmaturityndf":
                    return IngredientType.GrassesCoolHayMidMaturity;
                case "grassescoolseasonhaymaturendf":
                    return IngredientType.GrassesCoolHayMature;
                case "grassescoolseasonsilageallsamples":
                    return IngredientType.GrassesCoolSilageAllSamples;
                case "grassescoolseasonsilageimmaturendf":
                    return IngredientType.GrassesCoolSilageImmature;
                case "grassescoolseasonsilagemidmaturityndf":
                    return IngredientType.GrassesCoolSilageMidMaturity;
                case "grassescoolseasonsilagematurendf":
                    return IngredientType.GrassesCoolSilageMature;
                case "grasslegumemixturespredominantlygrasshemicellulosehayimmaturendf":
                    return IngredientType.GrassLegumeMixturesPredomGrassHayImmature;
                case "grasslegumemixturespredominantlygrasshemicellulosehaymidmaturityndf":
                    return IngredientType.GrassLegumeMixturesPredomGrassHayMidMaturity;
                case "grasslegumemixturespredominantlygrasshemicellulosehaymaturendf":
                    return IngredientType.GrassLegumeMixturesPredomGrassHayMature;
                case "grasslegumemixturespredominantlygrasshemicellulosesilageimmaturendf":
                    return IngredientType.GrassLegumeMixturesPredomGrassSilageImmature;
                case "grasslegumemixturespredominantlygrasshemicellulosesilagemidmaturityndf":
                    return IngredientType.GrassLegumeMixturesPredomGrassSilageMidMaturity;
                case "grasslegumemixturespredominantlygrasshemicellulosesilagematurendf":
                    return IngredientType.GrassLegumeMixturesPredomGrassSilageMature;
                case "grasslegumemixturesmixedgrassandlegumehemicellulosehayimmaturendf":
                    return IngredientType.GrassLegumeMixturesMixedGrassAndLegumeHayImmature;
                case "grasslegumemixturesmixedgrassandlegumehemicellulosehaymidmaturityndf":
                    return IngredientType.GrassLegumeMixturesMixedGrassAndLegumeHayMidMaturity;
                case "grasslegumemixturesmixedgrassandlegumehemicellulosehaymaturendf":
                    return IngredientType.GrassLegumeMixturesMixedGrassAndLegumeHayMature;
                case "grasslegumemixturesmixedgrassandlegumehemicellulosesilageimmaturendf":
                    return IngredientType.GrassLegumeMixturesMixedGrassAndLegumeSilageImmature;
                case "grasslegumemixturesmixedgrassandlegumehemicellulosesilagemidmaturityndf":
                    return IngredientType.GrassLegumeMixturesMixedGrassAndLegumeSilageMidMaturity;
                case "grasslegumemixturesmixedgrassandlegumehemicellulosesilagematurendf":
                    return IngredientType.GrassLegumeMixturesMixedGrassAndLegumeSilageMature;
                case "grasslegumemixturespredominantlylegumehemicellulosehayimmaturendf":
                    return IngredientType.GrassLegumeMixturesPredomLegumesHayImmature;
                case "grasslegumemixturespredominantlylegumehemicellulosehaymidmaturityndf":
                    return IngredientType.GrassLegumeMixturesPredomLegumesHayMidMaturity;
                case "grasslegumemixturespredominantlylegumehemicellulosehaymaturendf":
                    return IngredientType.GrassLegumeMixturesPredomLegumesHayMature;
                case "grasslegumemixturespredominantlylegumehemicellulosesilageimmaturendf":
                    return IngredientType.GrassLegumeMixturesPredomLegumesSilageImmature;
                case "grasslegumemixturespredominantlylegumehemicellulosesilagemidmaturityndf":
                    return IngredientType.GrassLegumeMixturesPredomLegumesSilageMidMaturity;
                case "grasslegumemixturespredominantlylegumehemicellulosesilagematurendf":
                    return IngredientType.GrassLegumeMixturesPredomLegumesSilageMature;
                case "hominy":
                    return IngredientType.Hominy;
                case "johnsongrass":
                    return IngredientType.JoghnsonGrass;
                case "kidneybeansextruded":
                    return IngredientType.KidneyBeansExtruded;
                case "kidneybeansraw":
                    return IngredientType.KidneyBeansRaw;
                case "kochia":
                    return IngredientType.Kochia;
                case "kochiasilage":
                    return IngredientType.KochiaSilage;
                case "lactose":
                    return IngredientType.Lactose;
                case "legumesforagepastureintensivelymanaged":
                    return IngredientType.LegumesForagePastureIntense;
                case "legumesforagehayallsamples":
                    return IngredientType.LegumesForageHayAllSamples;
                case "legumesforagehayimmaturendf":
                    return IngredientType.LegumesForageHayImmature;
                case "legumesforagehaymidmaturityndf":
                    return IngredientType.LegumesForageHayMidMaturity;
                case "legumesforagehaymaturendf":
                    return IngredientType.LegumesForageHayMature;
                case "legumesforagesilageallsamples":
                    return IngredientType.LegumesForageSilageAllSamples;
                case "legumesforagesilageimmaturendf":
                    return IngredientType.LegumesForageSilageImmature;
                case "legumesforagesilagemidmaturityndf":
                    return IngredientType.LegumesForageSilageMidMaturity;
                case "lentils":
                    return IngredientType.Lentils;
                case "legumesforagesilagematurendf":
                    return IngredientType.LegumesForageSilageMature;
                case "linseedflaxmealsolvent":
                    return IngredientType.LinSeedFlaxMealSolvent;
                case "linseedmeal":
                    return IngredientType.LinseedMeal;
                case "lupins":
                    return IngredientType.Lupins;
                case "lupinseed":
                    return IngredientType.LupinSeed;
                case "meadowhay":
                    return IngredientType.MeadowHay;
                case "meatandbonemeal":
                    return IngredientType.MeatBoneMeal;
                case "meatandbonemealphosphorusgreaterthanfourpercent":
                    return IngredientType.MeatAndBoneMealPhosphorusGreaterThanFourPercent;
                case "meatmeal":
                    return IngredientType.MeatMeal;
                case "meatmealrendered":
                    return IngredientType.MeatMealRendered;
                case "meatmeatandbonerendered":
                    return IngredientType.MeatMeatAndBoneRendered;
                case "millet":
                    return IngredientType.Millet;
                case "milletforagefresh":
                    return IngredientType.MilletForageFresh;
                case "milletforagehay":
                    return IngredientType.MilletForageHay;
                case "milletgrain":
                    return IngredientType.MilletGrain;
                case "milletsilage":
                    return IngredientType.MilletSilage;
                case "molassesbeet":
                    return IngredientType.MolassesBeet;
                case "molassesbeetsugar":
                    return IngredientType.MolassesBeetSugar;
                case "molassescane":
                    return IngredientType.MolassesCane;
                case "molassessugarcane":
                    return IngredientType.MolassesSugarCane;
                case "molassessugarbeets":
                    return IngredientType.MolassesSugarBeets;
                case "nativeprairiehay":
                    return IngredientType.NativePrairieHay;
                case "oats":
                    return IngredientType.Oats;
                case "oatforage":
                    return IngredientType.OatForage;
                case "oatgrain":
                    return IngredientType.OatGrain;
                case "oatsgrainrolled":
                    return IngredientType.OatsGrainRolled;
                case "oatgroats":
                    return IngredientType.OatGroats;
                case "oathay":
                    return IngredientType.OatHay;
                case "oatshayheaded":
                    return IngredientType.OatHayHeaded;
                case "oathulls":
                    return IngredientType.OatHulls;
                case "oatsrolleddehulled":
                    return IngredientType.OatsRolledDehulled;
                case "oatsnaked":
                    return IngredientType.OatsNaked;
                case "oatssilageheaded":
                    return IngredientType.OatSilageHeaded;
                case "oatstraw":
                    return IngredientType.OatStraw;
                case "oatlage":
                    return IngredientType.Oatlage;
                case "onions":
                    return IngredientType.Onions;
                case "orchardgrasshay":
                    return IngredientType.OrchardgrassHay;
                case "palmkernelexpelled":
                    return IngredientType.PalmKernelExpelled;
                case "palmkernelmeal":
                    return IngredientType.PalmKernelMeal;
                case "palmkernelmealmechanicalextracted":
                    return IngredientType.PalmKernelMealMech;
                case "peahulls":
                    return IngredientType.PeaHulls;
                case "peanuthay":
                    return IngredientType.PeanutHay;
                case "peanuthulls":
                    return IngredientType.PeanutHulls;
                case "peanutmeal":
                    return IngredientType.PeanutMeal;
                case "peanutmealexpelled":
                    return IngredientType.PeanutMealExpelled;
                case "peanutmealextracted":
                    return IngredientType.PeanutMealMech;
                case "peanutmealmechanicalextracted":
                    return IngredientType.PeanutMealMech;
                case "peanutmealsolvent":
                    return IngredientType.PeanutMealSolvent;
                case "peanutsilage":
                    return IngredientType.PeanutSilage;
                case "peas":
                    return IngredientType.Peas;
                case "peaproteinconcentrate":
                    return IngredientType.PeaProteinConcentrate;
                case "peaproteinisolate":
                    return IngredientType.PeaProteinIsolate;
                case "peavineforage":
                    return IngredientType.PeavineForage;
                case "peavinehay":
                    return IngredientType.PeavineHay;
                case "peavinesilage":
                    return IngredientType.PeavineSilage;
                case "petfoodbyproducts":
                    return IngredientType.PetFoodByProducts;
                case "popcorngrain":
                    return IngredientType.PopcornGrain;
                case "porcinesolublesdried":
                    return IngredientType.PorcineSolublesDried;
                case "potatobyproductdry":
                    return IngredientType.PotatoByproductDry;
                case "potatobyproductmeal":
                    return IngredientType.PotatoByProductMeal;
                case "potatobyproductwet":
                    return IngredientType.PotatoByproductWet;
                case "potatoprotein":
                    return IngredientType.PotatoProtein;
                case "potatoproteinconcentrate":
                    return IngredientType.PotatoProteinConcentrate;
                case "potatopeels":
                    return IngredientType.PotatoPeels;
                case "poultrybyproduct":
                    return IngredientType.PoultryByProduct;
                case "poultrybyproductmeal":
                    return IngredientType.PoultryByProductMeal;
                case "poultrymeal":
                    return IngredientType.PoultryMeal;
                case "potatoes":
                    return IngredientType.Potatoes;
                case "rice":
                    return IngredientType.Rice;
                case "ricebran":
                    return IngredientType.RiceBran;
                case "ricebrandefatted":
                    return IngredientType.RiceBranDefatted;
                case "ricebroken":
                    return IngredientType.RiceBroken;
                case "ricegrain":
                    return IngredientType.RiceGrain;
                case "ricehay":
                    return IngredientType.RiceHay;
                case "ricehulls":
                    return IngredientType.RiceHulls;
                case "ricepolished":
                    return IngredientType.RicePolished;
                case "riceproteinconcentrate":
                    return IngredientType.RiceProteinConcentrate;
                case "ricesilage":
                    return IngredientType.RiceSilage;
                case "rye":
                    return IngredientType.Rye;
                case "ryeannualfresh":
                    return IngredientType.RyeAnnualFresh;
                case "ryeannualsilagevegetative":
                    return IngredientType.RyeAnnualSilageVegetative;
                case "ryegrasshay":
                    return IngredientType.RyegrassHay;
                case "ryegrasssilage":
                    return IngredientType.RyegrassSilage;
                case "ryegrain":
                    return IngredientType.RyeGrain;
                case "safflowermeal":
                    return IngredientType.SafflowerMeal;
                case "safflowermealdehulled":
                    return IngredientType.SafflowerMealDehulled;
                case "safflowermealsolvent":
                    return IngredientType.SafflowerMealSolvent;
                case "salmonproteinhydrolysate":
                    return IngredientType.SalmonProteinHydrolysate;
                case "sesamemeal":
                    return IngredientType.SesameMeal;
                case "sesamemealmechanicalextracted":
                    return IngredientType.SesameMealMech;
                case "skimmilkpowder":
                    return IngredientType.SkimmedMilkPowder;
                case "skimmedmilkpowder":
                    return IngredientType.SkimmedMilkPowder;
                case "sorghum":
                    return IngredientType.Sorghum;
                case "sorghumdistillersdriedgrainswithsolubles":
                    return IngredientType.SorghumDistillersDriedGrainsWithSolubles;
                case "sorghumgraindryrolled":
                    return IngredientType.SorghumGrainDryRolled;
                case "sorghumgrainsteamflaked":
                    return IngredientType.SorghumGrainSteamFlaked;
                case "sorghumsilage":
                    return IngredientType.SorghumSilage;
                case "sorghumsudantypehay":
                    return IngredientType.SorghumSudanTypeHay;
                case "sorghumsudantypesilage":
                    return IngredientType.SorghumSudanTypeSilage;
                case "soybeanhay":
                    return IngredientType.SoybeanHay;
                case "soybeanhulls":
                    return IngredientType.SoybeanHulls;
                case "soybeanmealdehulledexpelled":
                    return IngredientType.SoybeanMealDehulledExpelled;
                case "soybeanmealdehulledsolventextracted":
                    return IngredientType.SoybeanMealDehulledSolventExtracted;
                case "soybeanmealenzymetreated":
                    return IngredientType.SoybeanMealEnzymeTreated;
                case "soybeanmealexpelled":
                    return IngredientType.SoybeanMealExpelled;
                case "soybeanmealfermented":
                    return IngredientType.SoybeanMealFermented;
                case "soybeanmealhighproteindehulledsolventextracted":
                    return IngredientType.SoybeanMealHighProteinDehulledSolventExtracted;
                case "soybeanmealhighproteinexpelled":
                    return IngredientType.SoybeanMealHighProteinExpelled;
                case "soybeanmeallowoligosaccharidedehulledsolventextracted":
                    return IngredientType.SoybeanMealLowOligosaccharideDehulledSolventExtracted;
                case "soybeanmeallowoligosaccharideexpelled":
                    return IngredientType.SoybeanMealLowOligosaccharideExpelled;
                case "soybeanmealhighcp":
                    return IngredientType.SoybeanMealHighCP;
                case "soybeanmeallowcp":
                    return IngredientType.SoybeanMealLowCP;
                case "soybeanmealexpellerscp":
                    return IngredientType.SoybeanMealExpellers;
                case "soybeanmealmechanicalextracted":
                    return IngredientType.SoybeanMealMech;
                case "soybeanmealsolventextracted":
                    return IngredientType.SoybeanMealSolvent;
                case "soybeanmealsolventextractedhighprotein":
                    return IngredientType.SoybeanMealSolventHighProtein;
                case "soybeanmealnonenzymaticallybrowned":
                    return IngredientType.SoybeanMealNonEnzymaticallyBrowned;
                case "soybeanmealsolventfourtyfourcp":
                    return IngredientType.SoybeanMealSolvent44;
                case "soybeanmealsolventfourtyeightcp":
                    return IngredientType.SoybeanMealSolvent48;
                case "soybeanmealheated":
                    return IngredientType.SoybeanMealHeated;
                case "soybeansfullfat":
                    return IngredientType.SoybeansFullFat;
                case "soybeanshighproteinfullfat":
                    return IngredientType.SoybeansHighProteinFullFat;
                case "soybeanslowoligosaccharidefullfat":
                    return IngredientType.SoybeansLowOligosaccharideFullFat;
                case "soybeanseed":
                    return IngredientType.SoybeanSeed;
                case "soybeanseedswhole":
                    return IngredientType.SoybeanSeedsWhole;
                case "soybeanseedswholeroasted":
                    return IngredientType.SoybeanSeedsWholeRoasted;
                case "soybeansilageearlymaturity":
                    return IngredientType.SoybeanSilageEarlyMaturity;
                case "soybeansilage":
                    return IngredientType.SoybeanSilage;
                case "soybeanstubble":
                    return IngredientType.SoybeanStubble;
                case "soybeansexpelled":
                    return IngredientType.SoybeansExpelled;
                case "soybeansextruded":
                    return IngredientType.SoybeansExptruded;
                case "soybeansroasted":
                    return IngredientType.SoybeansRoasted;
                case "soybeanswhole":
                    return IngredientType.SoybeansWhole;
                case "soyproteinconcentrate":
                    return IngredientType.SoyProteinConcentrate;
                case "soyproteinisolate":
                    return IngredientType.SoyProteinIsolate;
                case "sudangrassfresh":
                    return IngredientType.SudangrassFresh;
                case "sudangrasshay":
                    return IngredientType.SudangrassHay;
                case "sudangrasssilage":
                    return IngredientType.SudangrassSilage;
                case "sugarcanebagassesilage":
                    return IngredientType.SugarcaneBagrassSilage;
                case "sugarcanehay":
                    return IngredientType.SugarcaneHay;
                case "sugarcanesilage":
                    return IngredientType.SudangrassSilage;
                case "sugarbeetmolasses":
                    return IngredientType.SugarbeetMolasses;
                case "sugarbeetpulp":
                    return IngredientType.SugarBeetPulp;
                case "sugarbeetpulpdry":
                    return IngredientType.SugarbeetPulpDry;
                case "sugarcanemolasses":
                    return IngredientType.SugarcaneMolasses;
                case "sunflowerfullfat":
                    return IngredientType.SunflowerFullFat;
                case "sunflowerhulls":
                    return IngredientType.SunflowerHulls;
                case "sunflowermeal":
                    return IngredientType.SunflowerMeal;
                case "sunflowermealdehulledsolventextracted":
                    return IngredientType.SunflowerMealDehulledSolventExtracted;
                case "sunflowermealsolventextracted":
                    return IngredientType.SunflowerMealSolvent;
                case "sunflowermealsolvent":
                    return IngredientType.SunflowerMealSolvent;
                case "sunfloweroilseedswhole":
                    return IngredientType.SunflowerOilSeedsWhole;
                case "sunflowerscreenings":
                    return IngredientType.SunflowerScreenings;
                case "sunflowerseed":
                    return IngredientType.SunflowerSeed;
                case "sunflowersilage":
                    return IngredientType.SunflowerSilage;
                case "sunflowers":
                    return IngredientType.Sunflowers;
                case "switchgrasshay":
                    return IngredientType.SwitchgrassHay;
                case "tefflovegrasshay":
                    return IngredientType.TeffLovegrassHay;
                case "timothyhay":
                    return IngredientType.TimothyHay;
                case "tomatopomace":
                    return IngredientType.TomatoPomace;
                case "triticale":
                    return IngredientType.Triticale;
                case "triticaledistillersdriedgrainswithsolubles":
                    return IngredientType.TriticaleDistillersDriedGrainsWithSolubles;
                case "triticaleforagefresh":
                    return IngredientType.TriticaleForageFresh;
                case "triticalegrain":
                    return IngredientType.TriticaleGrain;
                case "triticalehay":
                    return IngredientType.TimothyHay;
                case "triticalesilage":
                    return IngredientType.TriticaleSilage;
                case "triticalesilageheaded":
                    return IngredientType.TriticaleSilageHeaded;
                case "wheatbran":
                    return IngredientType.WheatBran;
                case "wheatdistillersdriedgrainswithsolubles":
                    return IngredientType.WheatDistillersDriedGrainsWithSolubles;
                case "wheatforagefresh":
                    return IngredientType.WheatForageFresh;
                case "wheatgluten":
                    return IngredientType.WheatGluten;
                case "wheatgrain":
                    return IngredientType.WheatGrain;
                case "wheatgrainflaked":
                    return IngredientType.WheatGrainFlaked;
                case "wheatgrainrolled":
                    return IngredientType.WheatGrainRolled;
                case "wheathardred":
                    return IngredientType.WheatHardRed;
                case "wheatsoftred":
                    return IngredientType.WheatSoftRed;
                case "wheathay":
                    return IngredientType.WheatHay;
                case "wheathayheaded":
                    return IngredientType.WheatHayHeaded;
                case "wheatmiddlings":
                    return IngredientType.WheatMiddlings;
                case "wheatscreenings":
                    return IngredientType.WheatScreenings;
                case "wheatshorts":
                    return IngredientType.WheatShorts;
                case "wheypermeateeightypercentlactose":
                    return IngredientType.WheyPermeateLactose80;
                case "wheypermeateeightyfivepercentlactose":
                    return IngredientType.WheyPermeateLactose85;
                case "wheypermeatelactose":
                    return IngredientType.WheyPermeateLactose;
                case "wheypowder":
                    return IngredientType.WheyPowder;
                case "wheyproteinconcentrate":
                    return IngredientType.WheyPowderProteinConcentrate;
                case "wheypowderproteinconcentrate":
                    return IngredientType.WheyPowderProteinConcentrate;
                case "wheatsilage":
                    return IngredientType.WheatSilage;
                case "wheatsilageearlyhead":
                    return IngredientType.WheatSilageEarlyHead;
                case "wheatstraw":
                    return IngredientType.WheatStraw;
                case "wheywet":
                    return IngredientType.WheyWet;
                case "wheywetcattle":
                    return IngredientType.WheyWetCattle;
                case "wheydry":
                    return IngredientType.WheyDry;
                case "ammoniumphosphatedibasic":
                    return IngredientType.AmmoniumPhosphateDibasic;
                case "ammoniumphosphatemonobasic":
                    return IngredientType.AmmoniumPhosphateMonobasic;
                case "ammoniumsulfate":
                    return IngredientType.AmmoniumSulfate;
                case "bonemeal":
                    return IngredientType.BoneMeal;
                case "calciumcarbonate":
                    return IngredientType.CalciumCarbonate;
                case "calciumchlorideanhydrous":
                    return IngredientType.CalciumChlorideAnhyrdrous;
                case "calciumchloridedihydrate":
                    return IngredientType.CalciumChlorideDihydrate;
                case "calciumhydroxide":
                    return IngredientType.CalciumHydroxide;
                case "calciumoxide":
                    return IngredientType.CalciumOxide;
                case "calciumphosphatemonobasic":
                    return IngredientType.CalciumPhosphateMonobasic;
                case "calciumsulfatedihydrate":
                    return IngredientType.CalciumSulfateDihydrate;
                case "cobaltcarbonate":
                    return IngredientType.CobaltCarbonate;
                case "coppersulfatepentahydrate":
                    return IngredientType.CopperSulfatePentahydrate;
                case "dicalciumphosphate":
                    return IngredientType.DicalciumPhosphate;
                case "edta":
                    return IngredientType.EDTA;
                case "ironsulfate":
                    return IngredientType.IronSulfate;
                case "limestone":
                    return IngredientType.Limestone;
                case "limestonedolomiticmagnesium":
                    return IngredientType.LimestoneDilomiticMagnesium;
                case "magnesiumcarbonate":
                    return IngredientType.MagnesiumCarbonate;
                case "magnesiumchloridehexadydrate":
                    return IngredientType.MagnesiumChlorideHexahydrate;
                case "magnesiumhydroxide":
                    return IngredientType.MagnesiumHydroxide;
                case "magnesiumoxide":
                    return IngredientType.MagnesiumOxide;
                case "magnesiumsulfateheptahydrate":
                    return IngredientType.MagnesiumSulfateHeptahydrate;
                case "manganesecarbonate":
                    return IngredientType.MagnesiumCarbonate;
                case "manganeseoxide":
                    return IngredientType.ManganeseOxide;
                case "manganesesulfatemonohydrate":
                    return IngredientType.ManganeseSulfateMonohydrate;
                case "manganesesulfatepentahydrate":
                    return IngredientType.ManganeseSulfatePentahydrate;
                case "oystershellground":
                    return IngredientType.OystershellGround;
                case "beansphaselousbeans":
                    return IngredientType.PhaselousBeans;
                case "phosphatedeflourinated":
                    return IngredientType.PhosphateDeflourinated;
                case "phosphatemonomono":
                    return IngredientType.PhosphateMonoMono;
                case "phosphaterock":
                    return IngredientType.PhosphateRock;
                case "phosphaterocklowfluor":
                    return IngredientType.PhosphateRockLowFlour;
                case "phosphaterocksoft":
                    return IngredientType.PhosphateRockSoft;
                case "phosphoricacid":
                    return IngredientType.PhosphoricAcid;
                case "potassiumbicarbonate":
                    return IngredientType.PotassiumBicarbonate;
                case "potassiumcarbonate":
                    return IngredientType.PotassiumCarbonate;
                case "potassiumchloride":
                    return IngredientType.PotassiumChloride;
                case "potassiumiodide":
                    return IngredientType.PotassiumIodide;
                case "potassiumsulfate":
                    return IngredientType.PotassiumSulfate;
                case "saltsodiumchloride":
                    return IngredientType.SaltSodiumChloride;
                case "sodiumbicarbonate":
                    return IngredientType.SodiumBicarbonate;
                case "sodiumphosphatemonobasicmonohydrate":
                    return IngredientType.SodiumPhosphateMonobasicMonohydrate;
                case "sodiumselenite":
                    return IngredientType.SodiumSelenite;
                case "sodiumsulfatedecahydrate":
                    return IngredientType.SodiumSulfateDecahydrate;
                case "sodiumtripolyphosphate":
                    return IngredientType.SodiumTripolyphosphate;
                case "yeastbrewers":
                    return IngredientType.BrewersYeast;
                case "yeastethanol":
                    return IngredientType.YeastEthanol;
                case "yeastsinglecellprotein":
                    return IngredientType.YeastSingleCellProtein;
                case "yeasttorula":
                    return IngredientType.YeastTorula;
                case "urea":
                    return IngredientType.Urea;
                case "zincoxide":
                    return IngredientType.ZincOxide;
                case "zincsulfate":
                    return IngredientType.ZincSulfate;
                default:
                    throw new Exception(string.Format(Resources.ExceptionUnknowFeedTypeString, input));
            }
        }

        #endregion

        #region Constructors

        #endregion

        #region Fields

        #endregion

        #region Properties

        #endregion

        #region Private Methods

        #endregion

        #region Event Handlers

        #endregion
    }
}