//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Avalonia.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Avalonia.Core.Properties.FileResources", typeof(FileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Alberta_No_Styles {
            get {
                object obj = ResourceManager.GetObject("Alberta_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BC_No_Styles {
            get {
                object obj = ResourceManager.GetObject("BC_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Notices
        ///
        ///This software was designed primarily to encourage users to explore possible ways of reducing greenhouse gas emissions from farms. The estimates of emission are approximate, and may change appreciably as new scientific findings emerge. Agriculture and Agri-Food Canada does not warrant the reliability of this tool for uses other than education or exploratory gaming of possible practices.
        ///
        ///Copyright/Permission to Reproduce
        ///
        ///Material in this software were produced and/or compiled by Agr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Disclaimer_English {
            get {
                return ResourceManager.GetString("Disclaimer_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avis importants
        ///
        ///Ce logiciel a été conçu principalement pour encourager les utilisateurs à explorer des solutions possibles en vue de réduire les émissions de gaz à effet de serre produites par les exploitations agricoles. Les estimations sont approximatives et peuvent changer de façon appréciable si de nouvelles découvertes scientifiques voient le jour. Il s’agit d’un outil éducatif permettant de simuler des pratiques possibles. Agriculture et Agroalimentaire Canada ne garantit pas la fiabilité de cet ou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Disclaimer_French {
            get {
                return ResourceManager.GetString("Disclaimer_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MB_No_Styles {
            get {
                object obj = ResourceManager.GetObject("MB_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NB_No_Styles {
            get {
                object obj = ResourceManager.GetObject("NB_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NFLD_No_Styles {
            get {
                object obj = ResourceManager.GetObject("NFLD_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NS_No_Styles {
            get {
                object obj = ResourceManager.GetObject("NS_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ON_No_Styles {
            get {
                object obj = ResourceManager.GetObject("ON_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PEI_No_Styles {
            get {
                object obj = ResourceManager.GetObject("PEI_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] QC_No_Styles {
            get {
                object obj = ResourceManager.GetObject("QC_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SK_No_Styles {
            get {
                object obj = ResourceManager.GetObject("SK_No_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
