//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Avalonia.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Avalonia.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holos - a tool to estimate and reduce greenhouse gas emissions from farms.
        /// </summary>
        public static string AboutHolosMessage {
            get {
                return ResourceManager.GetString("AboutHolosMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string Alberta {
            get {
                return ResourceManager.GetString("Alberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holos Data Extraction Tool.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Chernozem.
        /// </summary>
        public static string BlackChernozem {
            get {
                return ResourceManager.GetString("BlackChernozem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia.
        /// </summary>
        public static string BritishColumbia {
            get {
                return ResourceManager.GetString("BritishColumbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown Chernozem.
        /// </summary>
        public static string BrownChernozem {
            get {
                return ResourceManager.GetString("BrownChernozem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate_Data.
        /// </summary>
        public static string ClimateDataExportDefaultName {
            get {
                return ResourceManager.GetString("ClimateDataExportDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coarse.
        /// </summary>
        public static string Coarse {
            get {
                return ResourceManager.GetString("Coarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron McPherson
        ///Hassan Afzaal.
        /// </summary>
        public static string ContributorsList {
            get {
                return ResourceManager.GetString("ContributorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Brown Chernozem.
        /// </summary>
        public static string DarkBrownChernozem {
            get {
                return ResourceManager.GetString("DarkBrownChernozem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Gray Chernozem.
        /// </summary>
        public static string DarkGrayChernozem {
            get {
                return ResourceManager.GetString("DarkGrayChernozem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holos - Irish version.
        /// </summary>
        public static string Disclaimer_Ireland {
            get {
                return ResourceManager.GetString("Disclaimer_Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dystric Brunisol.
        /// </summary>
        public static string DystricBrunisol {
            get {
                return ResourceManager.GetString("DystricBrunisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eutric Brunisol.
        /// </summary>
        public static string EutricBrunisol {
            get {
                return ResourceManager.GetString("EutricBrunisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ecozone &apos;{0}&apos;.
        /// </summary>
        public static string ExceptionUnknownEcozoneString {
            get {
                return ResourceManager.GetString("ExceptionUnknownEcozoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown soil type &apos;{0}&apos;.
        /// </summary>
        public static string ExceptionUnknownSoilTextureString {
            get {
                return ResourceManager.GetString("ExceptionUnknownSoilTextureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File.
        /// </summary>
        public static string ExportDefaultName {
            get {
                return ResourceManager.GetString("ExportDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferro Humic Podzol.
        /// </summary>
        public static string FerroHumicPodzol {
            get {
                return ResourceManager.GetString("FerroHumicPodzol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibrisol.
        /// </summary>
        public static string Fibrisol {
            get {
                return ResourceManager.GetString("Fibrisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string Fine {
            get {
                return ResourceManager.GetString("Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folisol.
        /// </summary>
        public static string Folisol {
            get {
                return ResourceManager.GetString("Folisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleysol.
        /// </summary>
        public static string Gleysol {
            get {
                return ResourceManager.GetString("Gleysol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Brown Luvisol.
        /// </summary>
        public static string GrayBrownLuvisol {
            get {
                return ResourceManager.GetString("GrayBrownLuvisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Luvisol.
        /// </summary>
        public static string GrayLuvisol {
            get {
                return ResourceManager.GetString("GrayLuvisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string HeadingRestartRequired {
            get {
                return ResourceManager.GetString("HeadingRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Data.
        /// </summary>
        public static string HeadingSavingData {
            get {
                return ResourceManager.GetString("HeadingSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder version.
        /// </summary>
        public static string HolosVersionNumber {
            get {
                return ResourceManager.GetString("HolosVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humic Gleysol.
        /// </summary>
        public static string HumicGleysol {
            get {
                return ResourceManager.GetString("HumicGleysol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humic Podzol.
        /// </summary>
        public static string HumicPodzol {
            get {
                return ResourceManager.GetString("HumicPodzol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humic Regosol.
        /// </summary>
        public static string HumicRegosol {
            get {
                return ResourceManager.GetString("HumicRegosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humic Vertisol.
        /// </summary>
        public static string HumicVertisol {
            get {
                return ResourceManager.GetString("HumicVertisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humisol.
        /// </summary>
        public static string Humisol {
            get {
                return ResourceManager.GetString("Humisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humo Ferric Podzol.
        /// </summary>
        public static string HumoFerricPodzol {
            get {
                return ResourceManager.GetString("HumoFerricPodzol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File.
        /// </summary>
        public static string ImportDefaultName {
            get {
                return ResourceManager.GetString("ImportDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Holos.
        /// </summary>
        public static string LabelAboutHolos {
            get {
                return ResourceManager.GetString("LabelAboutHolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row.
        /// </summary>
        public static string LabelAddRow {
            get {
                return ResourceManager.GetString("LabelAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LabelBack {
            get {
                return ResourceManager.GetString("LabelBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Monthly PPT?.
        /// </summary>
        public static string LabelCalculateMonthlyPPT {
            get {
                return ResourceManager.GetString("LabelCalculateMonthlyPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Data.
        /// </summary>
        public static string LabelClimateData {
            get {
                return ResourceManager.GetString("LabelClimateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string LabelContributors {
            get {
                return ResourceManager.GetString("LabelContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string LabelDisclaimer {
            get {
                return ResourceManager.GetString("LabelDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Year.
        /// </summary>
        public static string LabelEndYear {
            get {
                return ResourceManager.GetString("LabelEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string LabelExportToCSV {
            get {
                return ResourceManager.GetString("LabelExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Coordinate.
        /// </summary>
        public static string LabelFindCoordinate {
            get {
                return ResourceManager.GetString("LabelFindCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Climate Data.
        /// </summary>
        public static string LabelGetClimateData {
            get {
                return ResourceManager.GetString("LabelGetClimateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Coordinates.
        /// </summary>
        public static string LabelGetCoordinates {
            get {
                return ResourceManager.GetString("LabelGetCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Soil Data.
        /// </summary>
        public static string LabelGetSoilData {
            get {
                return ResourceManager.GetString("LabelGetSoilData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string LabelGithub {
            get {
                return ResourceManager.GetString("LabelGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holos official page.
        /// </summary>
        public static string LabelHolosOfficialPage {
            get {
                return ResourceManager.GetString("LabelHolosOfficialPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From CSV.
        /// </summary>
        public static string LabelImportFromCSV {
            get {
                return ResourceManager.GetString("LabelImportFromCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julian Day End.
        /// </summary>
        public static string LabelJulianEndDay {
            get {
                return ResourceManager.GetString("LabelJulianEndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julian Day Start.
        /// </summary>
        public static string LabelJulianStartDay {
            get {
                return ResourceManager.GetString("LabelJulianStartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LabelLatitude {
            get {
                return ResourceManager.GetString("LabelLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Polygons.
        /// </summary>
        public static string LabelLoadPolygons {
            get {
                return ResourceManager.GetString("LabelLoadPolygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LabelLongitude {
            get {
                return ResourceManager.GetString("LabelLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly PPT.
        /// </summary>
        public static string LabelMonthlyPPT {
            get {
                return ResourceManager.GetString("LabelMonthlyPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Coordinates.
        /// </summary>
        public static string LabelMultipleCoordinates {
            get {
                return ResourceManager.GetString("LabelMultipleCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Organic Matter in Soil.
        /// </summary>
        public static string LabelOrganicMatterSoil {
            get {
                return ResourceManager.GetString("LabelOrganicMatterSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Clay in Soil.
        /// </summary>
        public static string LabelPercentClayInSoil {
            get {
                return ResourceManager.GetString("LabelPercentClayInSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string LabelProvince {
            get {
                return ResourceManager.GetString("LabelProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string LabelSelectAllRows {
            get {
                return ResourceManager.GetString("LabelSelectAllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Coordinate.
        /// </summary>
        public static string LabelSingleCoordinate {
            get {
                return ResourceManager.GetString("LabelSingleCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Data.
        /// </summary>
        public static string LabelSoilData {
            get {
                return ResourceManager.GetString("LabelSoilData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Great Group.
        /// </summary>
        public static string LabelSoilGreatGroup {
            get {
                return ResourceManager.GetString("LabelSoilGreatGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil pH.
        /// </summary>
        public static string LabelSoilPh {
            get {
                return ResourceManager.GetString("LabelSoilPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Texture.
        /// </summary>
        public static string LabelSoilTexture {
            get {
                return ResourceManager.GetString("LabelSoilTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year.
        /// </summary>
        public static string LabelStartYear {
            get {
                return ResourceManager.GetString("LabelStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PET.
        /// </summary>
        public static string LabelTotalPET {
            get {
                return ResourceManager.GetString("LabelTotalPET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PPT.
        /// </summary>
        public static string LabelTotalPPT {
            get {
                return ResourceManager.GetString("LabelTotalPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string LabelUsefulLinks {
            get {
                return ResourceManager.GetString("LabelUsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string LabelYear {
            get {
                return ResourceManager.GetString("LabelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luvic Gleysol.
        /// </summary>
        public static string LuvicGleysol {
            get {
                return ResourceManager.GetString("LuvicGleysol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manitoba.
        /// </summary>
        public static string Manitoba {
            get {
                return ResourceManager.GetString("Manitoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melanic Brunisol.
        /// </summary>
        public static string MelanicBrunisol {
            get {
                return ResourceManager.GetString("MelanicBrunisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesisol.
        /// </summary>
        public static string Mesisol {
            get {
                return ResourceManager.GetString("Mesisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address field is empty. Please try again..
        /// </summary>
        public static string MessageEmptyAddress {
            get {
                return ResourceManager.GetString("MessageEmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address entered was incorrect. Please try again..
        /// </summary>
        public static string MessageIncorrectAddress {
            get {
                return ResourceManager.GetString("MessageIncorrectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the address for this coordinate. Please select a valid location..
        /// </summary>
        public static string MessageIncorrectLocationSelected {
            get {
                return ResourceManager.GetString("MessageIncorrectLocationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid coordinate was entered. Please check the latitude and longitude values and try again..
        /// </summary>
        public static string MessageInValidCoordinateEntered {
            get {
                return ResourceManager.GetString("MessageInValidCoordinateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needs to be restarted for this setting to take effect..
        /// </summary>
        public static string MessageRestartRequired {
            get {
                return ResourceManager.GetString("MessageRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data before closing the application. Please wait..
        /// </summary>
        public static string MessageSavingData {
            get {
                return ResourceManager.GetString("MessageSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brunswick.
        /// </summary>
        public static string NewBrunswick {
            get {
                return ResourceManager.GetString("NewBrunswick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfoundland.
        /// </summary>
        public static string Newfoundland {
            get {
                return ResourceManager.GetString("Newfoundland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territories.
        /// </summary>
        public static string NorthwestTerritories {
            get {
                return ResourceManager.GetString("NorthwestTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Scotia.
        /// </summary>
        public static string NovaScotia {
            get {
                return ResourceManager.GetString("NovaScotia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunavut.
        /// </summary>
        public static string Nunavut {
            get {
                return ResourceManager.GetString("Nunavut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string Ontario {
            get {
                return ResourceManager.GetString("Ontario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organic Cryosol.
        /// </summary>
        public static string OrganicCryosol {
            get {
                return ResourceManager.GetString("OrganicCryosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prince Edward Island.
        /// </summary>
        public static string PrinceEdwardIsland {
            get {
                return ResourceManager.GetString("PrinceEdwardIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string Quebec {
            get {
                return ResourceManager.GetString("Quebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regosol.
        /// </summary>
        public static string Regosol {
            get {
                return ResourceManager.GetString("Regosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete row(s)?.
        /// </summary>
        public static string RowDeleteMessage {
            get {
                return ResourceManager.GetString("RowDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        public static string Saskatchewan {
            get {
                return ResourceManager.GetString("Saskatchewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Province.
        /// </summary>
        public static string SelectProvince {
            get {
                return ResourceManager.GetString("SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your region.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language.
        /// </summary>
        public static string SelectYourLanguage {
            get {
                return ResourceManager.GetString("SelectYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil_Data.
        /// </summary>
        public static string SoilDataExportDefaultName {
            get {
                return ResourceManager.GetString("SoilDataExportDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solod.
        /// </summary>
        public static string Solod {
            get {
                return ResourceManager.GetString("Solod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solodized Solonetz.
        /// </summary>
        public static string SolodizedSolonetz {
            get {
                return ResourceManager.GetString("SolodizedSolonetz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solonetz.
        /// </summary>
        public static string Solonetz {
            get {
                return ResourceManager.GetString("Solonetz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sombric Brunisol.
        /// </summary>
        public static string SombricBrunisol {
            get {
                return ResourceManager.GetString("SombricBrunisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Cryosol.
        /// </summary>
        public static string StaticCryosol {
            get {
                return ResourceManager.GetString("StaticCryosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Contributor.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is a tool that provides users with access to climate and soil data for agricultural purposes. It is based on Holos, a tool developed by Agriculture and Agri-Food Canada to estimate greenhouse gas emissions from different farming practices. The application uses the NASA Power API to retrieve climate data for any location and time period, such as daily precipitation and evapotranspiration. The application also allows users to extract soil based data from Holos, such as soil group, soil textur [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextAboutPage {
            get {
                return ResourceManager.GetString("TextAboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string TitleDeleteRowDialog {
            get {
                return ResourceManager.GetString("TitleDeleteRowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be kept informed about  future versions, please send your contact information (including email address) to holos@canada.ca.
        /// </summary>
        public static string ToBeKeptInformedMessage {
            get {
                return ResourceManager.GetString("ToBeKeptInformedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbic Cryosol.
        /// </summary>
        public static string TurbicCryosol {
            get {
                return ResourceManager.GetString("TurbicCryosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertic Solonetz.
        /// </summary>
        public static string VerticSolonetz {
            get {
                return ResourceManager.GetString("VerticSolonetz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertisol.
        /// </summary>
        public static string Vertisol {
            get {
                return ResourceManager.GetString("Vertisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yukon.
        /// </summary>
        public static string Yukon {
            get {
                return ResourceManager.GetString("Yukon", resourceCulture);
            }
        }
    }
}
