//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Integration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Integration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,dead,,
        ///2,dead,,
        ///3,dead,,
        ///4,37.69911184,28.27433388,
        ///5,dead,,
        ///6,dead,,
        ///7,40.8407045,50.26548246,
        ///8,59.69026042,,
        ///9,dead,,
        ///10,45.55309348,,
        ///11,43.98229715,,
        ///12,49.63716393,34.87167845,
        ///13,65.97344573,,
        ///14,dead,,
        ///15,34.24335992,,
        ///16,73.19910883,,
        ///17,60.00441968,,
        ///18,46.18141201,50.26548246,
        ///19,64.71680866,,
        ///20,51.52211952,62.20353454,
        ///21,33.61504139,,
        ///22,53.40707511,41.15486376,
        ///23,45.86725274,,
        ///24,32.35840433,52.77875658,38.01327111
        ///25,dead,,
        ///26,44.29645642,43.98229715,
        ///27,64.40264 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ash {
            get {
                return ResourceManager.GetString("ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree #,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38
        ///1,57.4911,62.2035,60.6327,58.1195,57.4911,54.3496,65.3451,64.0885,70.6858,65.031,62.8319,50.2655,45.5531,,,,,,,,,,,,,,,,,,,,,,,,,
        ///2,47.438,64.7168,32.3584,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///3,31.4159,40.5265,61.5752,59.7531,41.7832,31.7301,67.8584,47.7522,63.7743,51.5221,63.7743,72.5708,58.4336,33.3009,59.0619,32.0442,42.0973,47.1239,65.3451,52.4646,,,,,,,,,,,,,,,,,,
        ///4,54.0354,67.8584,39.8982, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string caragana {
            get {
                return ResourceManager.GetString("caragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Caragana,Dead,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///2,Caragana,116.8672467,89.84954989,132.2610507,114.0398133,88.9070721,141.9999879,188.1814,120.6371579,87.9645943,170.5884811,34.55751919,136.0309619,128.4911395,114.6681319,61.88937528,114.3539726,123.150432,112.7831763,127.862821,,,,,,,,,,,,,,,,,,,
        ///3,Caragana,66.91592352,28.27433388,51.99335842,54.72654403,83.28362125,55.92034923,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///4,Ash,458.6725274,411.5486376,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///5,Caragana,108.0707873, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string caragana_and_ash {
            get {
                return ResourceManager.GetString("caragana_and_ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,105.2433539,
        ///2,Dead,
        ///3,69.74335691,
        ///4,67.85840132,
        ///5,72.25663103,
        ///6,98.33185006,
        ///7,96.76105373,
        ///8,Dead,
        ///9,97.075213,
        ///10,94.24777961,
        ///11,33.30088213,16.65044106
        ///12,95.50441667,
        ///13,Dead,
        ///14,26.38937829,54.97787144
        ///15,84.82300165,
        ///16,93.93362034,
        ///17,72.25663103,
        ///18,92.04866475,
        ///19,76.96902001,
        ///20,92.36282402,
        ///21,Dead,
        ///22,108.6991058,
        ///23,82.30972752,
        ///24,86.07963871,
        ///25,83.88052385,
        ///26,116.2389282,
        ///27,91.42034622,
        ///.
        /// </summary>
        internal static string colorado_spruce {
            get {
                return ResourceManager.GetString("colorado_spruce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year,Julian day,Mean Daily Air Temperature,Mean Daily Precipitation,Mean Daily PET
        ///1912,1,-15.6,0,0
        ///1912,2,-17.5,2,0
        ///1912,3,-17.2,0,0
        ///1912,4,-15.3,0,0
        ///1912,5,-20.8,2.5,0
        ///1912,6,-24.2,0,0
        ///1912,7,-18.4,0.8,0
        ///1912,8,-13.1,0,0
        ///1912,9,-22.2,0.8,0
        ///1912,10,-30.3,0.5,0
        ///1912,11,-30,0,0
        ///1912,12,-11.7,0,0
        ///1912,13,-10,0,0
        ///1912,14,-16.7,0,0
        ///1912,15,-1.2,0,0
        ///1912,16,0.6,8.6,0
        ///1912,17,-9.4,0,0
        ///1912,18,-19.7,0,0
        ///1912,19,-12,0,0
        ///1912,20,-2.5,0,0
        ///1912,21,4.8,0,0
        ///1912,22,2.2,0,0
        ///1912,23,-3.3,0,0
        ///1912,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lethbridge_DailyVariableClimateData_1912_2019 {
            get {
                return ResourceManager.GetString("Lethbridge_DailyVariableClimateData_1912_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,74,89,72
        ///2,129,104,
        ///3,Dead,,
        ///4,87,85,
        ///5,115,86,50
        ///6,95,56,50
        ///7,68,100,
        ///8,52,71,
        ///9,100,,
        ///10,31,38,
        ///11,109,,
        ///12,76,,
        ///13,52,,
        ///14,74,94,
        ///15,101,,
        ///16,90,,
        ///17,53,69,89
        ///18,dead,,
        ///19,61,97,
        ///20,94,98,
        ///21,129,,
        ///22,99,,
        ///23,47,,
        ///24,95,,
        ///25,93,87,98
        ///26,69,97,
        ///27,115,,
        ///28,39,,
        ///29,107,53,
        ///30,117,,
        ///31,dead,,
        ///32,123,80,
        ///33,dead,,
        ///34,92,,
        ///35,107,,
        ///36,55,,
        ///37,60,,
        ///38,62,,
        ///39,97,84,128
        ///40,dead,,
        ///41,dead,,
        ///42,56,,
        ///43,dead,,
        ///44,69,,
        ///45,65,41,
        ///46,53,50,
        ///47,86,,
        ///48,84,,
        ///49,77,65,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string siberian_elm {
            get {
                return ResourceManager.GetString("siberian_elm", resourceCulture);
            }
        }
    }
}
